### PR TITLE
fix(input): make md-maxlength validation happen on initialization

### LINKED ISSUE #10320: md-maxlength validation doesn't happen on initialization
**Actual Behavior**:
 -  `What is the issue? *` Using md-maxlength="MAX" on an input field that initializes to some value of length > "MAX", the md-maxlength validation does not happen, and the input field is considered valid.
 -  `What is the expected behavior?` The input field to be considered invalid on initialization.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/jessika/pen/MJvxKE
 -  `Details:` I created two input fields, one using md-maxlength for character limit validation, and one using ng-maxlength. Both have the same initial values and same character limit. You should be able to see that the field using md-maxlength is still valid and the field using ng-maxlength is marked invalid. I would expect that both fields be invalid.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1, 1.1.0

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 56.0.2924.76 (64-bit)
 -  `OS: *` Ubuntu
 -  `Stack Traces:` N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

### PR DESCRIPTION
**Pull request by feloy**
## PR Checklist
Please check that your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

When an input has an md-maxlength attribute and an initial value longer than this maxlength, no error is triggered until the input value is changed.

Issue Number: #10320 

## What is the new behavior?

When an input has an md-maxlength attribute and an initial value longer than this maxlength, an error is triggered at initialization. 

Note that the error message is not shown at initialization but only when the focus leave the input (without content changes), which seems to be the correct behavior (in a similar way, for 'required' input with empty initial value, no message is displayed at initialization).

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Closes #10320

### CODE REVIEW

**Comment by Splaktar** [comment]
Same as https://github.com/angular/material/pull/11149#issuecomment-370247813, Please add "Closes #10320" to the footer of your commit message as detailed in the [commit message guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format). Just adding it the PR description is not enough as that won't trigger the issue to be closed on merge or show up in the changelog properly.

File: src/components/input/input.js [hunk 1]
```diff
@@ -634,11 +634,25 @@ function mdMaxlengthDirective($animate, $mdUtil) {
   };
 
   function postLink(scope, element, attr, ctrls) {
-    var maxlength;
+    var maxlength = Number.parseInt(attr.mdMaxlength);
+    if (isNaN(maxlength)) maxlength = -1;
```
Comment (Splaktar) [inline src/components/input/input.js]: Should this use `!angular.isNumber(maxlength)` to be consistent with line 645, or is there a reason that `isNaN` better here?

File: src/components/input/input.js [hunk 2]
```diff
@@ -663,23 +677,11 @@ function mdMaxlengthDirective($animate, $mdUtil) {
...
-        renderCharCount();
-
-        return ( modelValue || element.val() || viewValue || '' ).length <= maxlength;
-      };
     });
 
     function renderCharCount(value) {
       // If we have not been appended to the body yet; do not render
-      if (!charCountEl.parent) {
+      if (!charCountEl || !charCountEl.parent) {
```
Comment (Splaktar) [inline src/components/input/input.js]: Is `||` correct here? Should this be `&&`?

File: src/components/input/input.js (hunk 1 above)
Comment (feloy) [reply src/components/input/input.js]: No, that's not equivalent here, because angular.isNumber(NaN) returns true but in this case, we do not want to keep NaN.

File: src/components/input/input.js (hunk 2 above)
Comment (feloy) [reply src/components/input/input.js]: We now have to check that charCountEl is not undefined or charCountEl.text will fail in the following lines in some cases (because charCountEl is initialized at nextTick and renderCharCount can now be called before nextTick, from validator).

Comment (Splaktar) [reply src/components/input/input.js]: OK, can you please update the comment as well?

File: src/components/input/input.js (hunk 1 above)
Comment (Splaktar) [reply src/components/input/input.js]: Ah yes, I thought that `angular.isNumber()` was smarter than it actually is.

**Comment by Splaktar** [comment]
Btw, amending commits is the best way to keep your changes in a single commit when updates are needed. Then force push to your branch is the best way to sync those updates to the branch.

**Comment by Splaktar** [comment]
Looks great! Thank you for your patience. I've sent this over to the caretaker to have presubmit tests run.

**Comment by Splaktar** [comment]
This is currently triggering some presubmit failures that appear to be flakes (i.e. from flaky tests, not actual real failures). This is being looked at internally by Google. No work is needed on your side at this time.

**Comment by Splaktar** [comment]
I re-ran the failing build steps in Travis and everything is green now 😃

**Comment by jelbourn** [comment]
This fails google presubmit because `Number.parseInt` is not supported in IE11

File: src/components/input/input.js [hunk 3]
```diff
@@ -634,11 +634,25 @@ function mdMaxlengthDirective($animate, $mdUtil) {
   };
 
   function postLink(scope, element, attr, ctrls) {
-    var maxlength;
+    var maxlength = Number.parseInt(attr.mdMaxlength);
```
Comment (Splaktar) [inline src/components/input/input.js]: As pointed out by Jeremy, `Number.parseInt` is not supported in IE11. So we'll need to use something different here.

It looks like the global [parseInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt) should work?
MDN also points out that [Number.parseInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt) has no IE support.

Comment (feloy) [reply src/components/input/input.js]: I've used the global parseInt instead
