### PR TITLE
fix(autocomplete): properly show dropdown on focus when minlength is met

### LINKED ISSUE #9283: md-autocomplete: dropdown not showing on focus if min length is met
`md-autocomplete` doesn't show listed suggestions when the chips are closed, for varying list of suggestions.

**Scenario:** I want to show suggestions only for the chips that are not added. Initially, all the chips are added, so there are no more chips left to add - no suggestions, which is fine. When a chip is closed and the input field is focused, there are still no suggestions but ideally there should be one chip in the suggestions list. The suggestions appear only if one or more characters are typed in. 

`md-autocomplete` should re-render the items even when the query string length is 0, but seems like it is set to 1. This can be inferred by observing the filter function defined in `md-items` which doesn't get triggered, when the query string is empty.

[CodePen Link](http://codepen.io/sgsvenkatesh/pen/LkrdPW)
Delete the added chips and focus on the input field. Observe that no suggestions for the closed chips are being displayed by `md-autocomplete`.

### PR DESCRIPTION
**Pull request by DevVersion**
Currently the `md-autocomplete` shows its dropdown only by changing the `searchText` from `null` to an empty string.

> This triggered a searchText change, which resulted in triggering a query.

This approach doesn't seem to be very elegant.

> The autocomplete should manually trigger a query and possibly open the dropdown if matches are available.

--
@topherfangio Can you take a look (especially on the chips with autocomplete behavior)
@ThomasBurleson I consider this as too risky for 1.1.0 (specifically the behavior with the chips)

Fixes #9283. Closes #9288. Closes #9289.

### CODE REVIEW

File: src/components/autocomplete/js/autocompleteController.js [hunk 1]
```diff
@@ -589,10 +591,19 @@ function MdAutocompleteCtrl ($scope, $element, $mdUtil, $mdConstant, $mdTheming,
...
+  }
+
+  /**
+   * Determines whether the autocomplete is able to query within the current state.
+   * @returns {boolean}
+   */
+  function isSearchable() {
+    if (ctrl.loading && !hasMatches()) return false; // No query when query is in progress.
+    else if (hasSelection()) return false;           // No query if there is already a selection
+    else if (!hasFocus) return false;                // No query if the input does not have focus
```
Comment (topherfangio) [inline src/components/autocomplete/js/autocompleteController.js]: Quick note: I don't think the `else if` is necessary here since you're doing a return. I'm really not sure why I had that in my `shouldHide()` code...

**Comment by topherfangio** [comment]
Code-wise it looks pretty good. I'll need to do some manual testing to make sure it works as expected.

**Comment by topherfangio** [comment]
@ThomasBurleson LGTM :+1:

File: src/components/chips/js/chipsController.js [hunk 2]
```diff
@@ -435,7 +435,17 @@ MdChipsCtrl.prototype.removeChip = function(index) {
...
 MdChipsCtrl.prototype.removeChipAndFocusInput = function (index) {
   this.removeChip(index);
-  this.onFocus();
+
+  if (this.autocompleteCtrl) {
+    // Always hide the autocomplete dropdown before focusing the autocomplete input.
+    // Wait for the input to move horizontally, because the chip was removed.
+    // This can lead to an incorrect dropdown position.
+    this.autocompleteCtrl.hidden = true;
+    this.$mdUtil.nextTick(this.onFocus.bind(this));
```
Comment (tuhoojabotti) [inline src/components/chips/js/chipsController.js]: @DevVersion I updated to 1.1.1 and this breaks, because this.$mdUtil is undefined. It is never assigned in the constructor.

Comment (DevVersion) [inline src/components/chips/js/chipsController.js]: Known issue - see https://github.com/angular/material/pull/9528
