### PR TITLE
fix(gestures): fix the swipe and scrolling issues on touch devices"

### LINKED ISSUE #10187: md-slider is not working in chrome 55 version in Android Phones
**Actual Behavior**:
Drag of slider is not working properly only click is working

**CodePen** (or steps to reproduce the issue): *

Open the demo link of angular material in Chrome 55 on Android Phone
https://material.angularjs.org/latest/demo/slider

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:`0.11.4

Note :- these are versions of my current app it is not working for even 1.1.1 version of angular material

**Additional Information**:
 -  `Browser Type: *`Chrome
 -  `Browser Version: *` 55
 -  `OS: *`Android
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

### PR DESCRIPTION
**Pull request by mohammadrafigh**
Fixes #10187, #10145.

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@mohammadrafigh - your Pull Request is failing with [Travis testing](https://travis-ci.org/angular/material/jobs/207551932). Please fix before we consider reviewing and merging.

**Comment by mohammadrafigh** [comment]
@ThomasBurleson oops, thanks forgot to remove that one.

**Comment by mohammadrafigh** [comment]
@ThomasBurleson oh no it's better to keep the tests for pointercancel event but instead expect .not.toHaveBeenCalled instead. I added back and fixed the test.

**Comment by ThomasBurleson** [comment]
@DevVersion - please review.

File: src/core/services/gesture/gesture.js [hunk 1]
```diff
@@ -643,7 +643,9 @@ function attachToDocument( $mdGesture, $$MdGestureHandler ) {
     updatePointerState(ev, pointer);
     pointer.endTime = +Date.now();
 
-    runHandlers('end', ev);
+    if (ev.type !== 'pointercancel') {
```
Comment (EladBezalel) [inline src/core/services/gesture/gesture.js]: Can you shortly explain why?

Comment (mohammadrafigh) [inline src/core/services/gesture/gesture.js]: Regarding to issues I mentioned in commit message, In chromium/chrome engine and webview in android there is a problem with angular material implementation of gestures. The problem is when we have swipable tabs with scrollable content dragging page to scroll fires pointercancel and causes to swipe to the other tab. The problem also can occure where ever we use drag and swipe together. So I excluded pointercancel from events to be handled by handler functions. If you want I can provide codepen to test, but the discussion on #10145 describes the issue well.

**Comment by EladBezalel** [comment]
@ThomasBurleson @jelbourn overall this fix seems legit, do we have a gestures expert somewhere ?

**Comment by mohammadrafigh** [comment]
it's funny! the PR marked for 1.1.4 but 1.1.4 released and the PR is still here.

**Comment by EladBezalel** [comment]
@mohammadrafigh though it was marked for 1.1.4, it seems like it didn't got merged in cause of the branch conflicts and got missed by the release, please rebase and let's get it in.

File: src/core/services/gesture/gesture.js (hunk 1 above)
Comment (theLufenk) [inline src/core/services/gesture/gesture.js]: Refer to our discussion in #10145

Pointercancel can be fired before pointerup. And that might mean that pointerup will not be fired. This is not good because a lot of cleanup and rollback logic often resides in the end event handler.

A fix of it might be browser detection based IMHO

**Comment by ThomasBurleson** [comment]
@mohammadrafigh - please rebase and squash your commits.

**Comment by EladBezalel** [comment]
@mohammadrafigh can you please rebase and squash your commits?

**Comment by mohammadrafigh** [comment]
@ThomasBurleson @EladBezalel sure I will do it tonight, sorry for late reply I was busy

**Comment by mohammadrafigh** [comment]
@ThomasBurleson @EladBezalel did it

**Comment by rhclayto** [comment]
Any news when 1.1.5 will come out with this new fix? It's much needed.

**Comment by sdpillay** [comment]
Any update on this? much needed for us too.

**Comment by rhclayto** [comment]
All checks passed, needs:merge. Does this mean this is ready to go in?

**Comment by axedre** [comment]
C'mon people, make this happen! ;)

**Comment by ThomasBurleson** [comment]
@rhclayto - preparing to merge for master. Thank you.

**Comment by sdpillay** [comment]
Desperately waiting on this

**Comment by axedre** [comment]
Ditto.


--
Andrea

2017-06-19 21:55 GMT+02:00 sdpillay <notifications@github.com>:

**Comment by sdpillay** [comment]
Any update when this will make it?
