### PR TITLE
fix(tabs): remove manual pagination sizing algorithm

### LINKED ISSUE #9429: tabs issue with 1.1.0
md-pagination-wrapper width is 1px less from what it should be generated, and this makes last tab to disappear from the bar
untithjkhkhkled-1

when i set 1px more it works ok, this issue happen with all may tabs after updating to 1.1.0 from rc5

### PR DESCRIPTION
**Pull request by clshortfuse**
Since tabs now use flexbox for sizing, manually sizing is no longer needed.
This solves issues related tabs inside flexible containers like dialogs.

* Remove updatePagingWidth() function
* Revert width to default values

Fixes #9429

### CODE REVIEW

**Comment by clshortfuse** [comment]
@ErinCoughlan this should solve your issue

Just to clarify, this changes the width of the `paginator`, not the actual tab buttons. 

Tested with http://codepen.io/shortfuse/pen/LbXVWP

- [ ] IE11
- [ ] Edge
- [ ] Safari
- [ ] Safari Mobile
- [ ] Chrome
- [ ] Firefox

**Comment by ThomasBurleson** [comment]
@clshortfuse - nice work.

**Comment by bvahdat** [comment]
@clshortfuse @ErinCoughlan please see #10386

**Comment by Splaktar** [comment]
This appears to have broken the display of tabs when pagination is needed on IE11: https://github.com/angular/material/issues/10406#issuecomment-382279969

File: src/components/tabs/js/tabsController.js [hunk 1]
```diff
@@ -606,23 +606,10 @@ function MdTabsController ($scope, $element, $window, $mdConstant, $mdTabInkRipp
...
 
-  /**
-   * Sets or clears fixed width for md-pagination-wrapper depending on if tabs should stretch.
-   */
-  function updatePagingWidth() {
-    var elements = getElements();
-    if (shouldStretchTabs()) {
-      angular.element(elements.paging).css('width', '');
-    } else {
-      angular.element(elements.paging).css('width', calcPagingWidth() + 'px');
```
Comment (Splaktar) [inline src/components/tabs/js/tabsController.js]: This was the only call to `calcPagingWidth()` but that function wasn't removed as is currently dead code.
