### PR TITLE
fix(select): Ensure `md-no-asterisk` attribute works.

### LINKED ISSUE #9339: md-select: md-no-asterisk not working
**Actual Behavior**:
 -  Having an md-select with the required attribute and a placeholder attribute. 
 -  I would expect to disable the appended asterisk on the placeholder with the md-no-asterisk attribute. But this does not work, the asterisk is appended.

**CodePen** (or steps to reproduce the issue): See behavior description.
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version: 1.5.8`
 -  `Angular Material Version: 1.1.0`

**Additional Information**:
 -  `Browser Type: Google Chrome`
 -  `Browser Version: 52`
 -  `OS: Windows 10`
 -  `Stack Traces:`

### PR DESCRIPTION
**Pull request by topherfangio**
After a recent change to the asterisk colors, the `md-no-asterisk` option was no longer working.

 - Update code to add a new `.md-no-asterisk` CSS class and fix styles.
 - Add appropriate tests.
 - Add `md-no-asterisk="false"` to demo so users can easily turn it on
   and test the fixed functionality.

Fixes #9339.

### CODE REVIEW

File: src/components/select/select.js [hunk 1]
```diff
@@ -74,7 +74,8 @@ angular.module('material.components.select', [
  * @param {expression=} md-selected-text Expression to be evaluated that will return a string
  * to be displayed as a placeholder in the select input box when it is closed.
  * @param {string=} placeholder Placeholder hint text.
- * @param md-no-asterisk {boolean=} When set to true, an asterisk will not be appended to the floating label.
+ * @param md-no-asterisk {boolean=} When set to true, an asterisk will not be appended to the
```
Comment (ThomasBurleson) [inline src/components/select/select.js]: Why is this an opt-out? Would an opt-in not be a better approach?

Comment (topherfangio) [inline src/components/select/select.js]: I have always pushed for the opt-in approach; however, this has been around since before 1.0 (before I joined the team I think) so I don't think we should change the API at this point.

All I did here was add a note about it only being evaluated once; not being watched.

**Comment by ThomasBurleson** [comment]
This seems so inverted backwards....
