### PR TITLE
fix(select): md-select-header closes on mouse click when not using multiple

### LINKED ISSUE #11969: select(header): closes when filter input is focused
## Bug

# Demo and steps to reproduce the issue

**Demo URL (required)***:  
With AngularJS Material Design v1.1.21: https://codepen.io/Axeldorf/pen/ExPGOpM
With AngularJS Material Design v1.1.24: https://codepen.io/Axeldorf/pen/yLeGQez

#### Detailed Reproduction Steps
1. Open selector.
1. Click on filter input

### Explain the expected behavior
On focusing filter input, select element is not closed and user can write any filter.

### Explain the current behavior
On focusing filter input, select element is closed and user can't write any filter.

### Discuss the use-case or motivation for changing the existing behavior
User wants to filter options in select, so when user clicks on input to write select must be opened.

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.7.8
- AngularJS Material: 1.1.21 (works), 1.1.22+ (doesn't work)
- OS: Ubuntu 18.04
- Browsers: Chrome.

### PR DESCRIPTION
**Pull request by Splaktar**
## PR Checklist
Please check that your PR fulfills the following requirements:
- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [ ] Tests for the changes have been added or this is not a bug fix / enhancement
- [x] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
- select with `md-select-header` closes on mouse click of the header's `input` when not using multiple

Issue Number: 
Fixes #11969

## What is the new behavior?
- if the click event came from within a `md-select-header`, `stopImmediatePropagation()`
  to keep the menu from closing
- fix demo's input being too short to display label when 'Kale' is selected
- rename some events and add types
- update select header input's placeholder and add an aria-label

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Splaktar** [comment]
This has been cherry picked into the `1.1.x` branch as well.

File: src/components/select/select.js [hunk 1]
```diff
@@ -688,19 +688,33 @@ function SelectMenuDirective($parse, $mdUtil, $mdConstant, $mdTheming) {
...
       var optionCtrl = option && angular.element(option).data('$mdOptionController');
-      if (!option || !optionCtrl) return;
-      if (option.hasAttribute('disabled')) {
-        ev.stopImmediatePropagation();
-        return false;
+
+      if (!option || !optionCtrl) {
+        // Avoid closing the menu when the select header's input is clicked
+        if (mouseEvent.target && mouseEvent.target.parentNode &&
+          mouseEvent.target.parentNode.tagName === 'MD-SELECT-HEADER') {
```
Comment (corvinb) [inline src/components/select/select.js:711]: <input>'s are usually inside <md-input-container>'s and this check would return false in this case. :(

Comment (Splaktar) [reply src/components/select/select.js:711]: @corvinb can you please open a new issue with a reproduction?
