### PR TITLE
fix(mdPanel): Panel and tooltip theming

### LINKED ISSUE #10030: fix(mdPanel): Theming is not initialized on certain panel implementations.
**Actual Behavior**:
 -  `What is the issue? *` If theming doesn't get initialized on `mdPanel` components, i.e. `mdTooltip`, then the color styling falls back to the default `mdPanel` styling.
 -  `What is the expected behavior?` Theming should always be initialized.

**CodePen** (or steps to reproduce the issue): *
 -  Before theming problem:
pasted image at 2016_11_16 05_13 pm
 -  After theming problem:
pasted image at 2016_11_16 05_13 pm 1

**Angular Versions**: *
 -  `Angular Version:` Latest
 -  `Angular Material Version:` Master

**Additional Information**:
 -  `Browser Type: *` All
 -  `Browser Version: *` Latest
 -  `OS: *` All
 -  `Stack Traces:` N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

### PR DESCRIPTION
**Pull request by bradrich**
- Initialized theming through `$mdTheming` on the panel element and container after the panel is created.
 - Fixed the panel and tooltip theme Sass files to remove unthemed styles and complicated syntax.
 - Removed an unnecessary `$mdTheming` call from the tooltip directive.

Fixes #10030

### CODE REVIEW

**Comment by ErinCoughlan** [comment]
This appears to fix the tooltip, but not the panel backdrop. The theme is still not applied to the backdrop.

**Comment by bradrich** [comment]
It seemed to work in my tests. How are you isolating it to get these results?

**Comment by bradrich** [comment]
Were you able to see where the `$mdTheming` calls were made on the `panelContainer` and the `panelEl`? The `panelContainer` is the backdrop of the panel API?

**Comment by ErinCoughlan** [comment]
I tested this by running the presubmit and patching it into our code where I could see the tooltip and a standalone panel.

So you can also see the standalone panel, if you temporarily add `hasBackdrop` to the tooltip panel config, no backdrop appears.

**Comment by ErinCoughlan** [comment]
For more information, `mdTheming` is called for the tooltip panel and the tooltip outer wrapper, but not for the backdrop panel or the backdrop outer wrapper.

**Comment by ErinCoughlan** [comment]
Ahha! Got it!

For the backdrop, there is no positionConfig, so the `addStyles` method resolves without hitting the `$mdTheming` call.

If you add the two `$mdTheming` lines at the beginning of `hideAndResolve` in addition to the current location, the backdrop appears the right color.

**Comment by bradrich** [comment]
Very cool. I am updating this now.

**Comment by bradrich** [comment]
Would it be better to put it here:  https://github.com/angular/material/blob/master/src/components/panel/panel.js#L1662? The `hideAndResolve` function could be called more than once. However, I don't think that the `$mdTheming` call happening more than once is a bad thing...

**Comment by bradrich** [comment]
@ErinCoughlan Give this a check and see what you think.

File: src/components/panel/panel.js [hunk 1]
```diff
@@ -1679,18 +1687,33 @@ MdPanelRef.prototype._addStyles = function() {
...
+
       resolve(self);
     });
   });
 };
 
 
 /**
+ * Sets the `$mdTheming` classes on the `panelContainer` and `panelEl`.
+ * @method setTheming
```
Comment (ErinCoughlan) [inline src/components/panel/panel.js]: This line isn't needed, `@method` is only used for the ngdoc, but this isn't public.

**Comment by ThomasBurleson** [comment]
@jelbourn - important fix.
