### PR TITLE
fix(md-contact-chips): support md-min-length on md-contact-chips.

### LINKED ISSUE #2423: md-contact-chips show list on focus
Hi,

Is there any possibility to show contact list on search box focus (before typing)?
I'd like to use contact chips to choose tags (from short list of tags - instead of multiselect solutions) and I like to show this list on focus on the search box (before user type anything).

Is it possible?

### PR DESCRIPTION
**Pull request by lievenjanssen**
Add md-min-length to md-contact-chips and propagate attribute to md-autocomplete.
Add md-has-not-found=true attribute to md-autocomplete.

Fixes #2423.

### CODE REVIEW

**Comment by lievenjanssen** [comment]
@topherfangio @ThomasBurleson any reason why nothing happened yet (e.g. 'needs review' tags) on this PR?

File: src/components/chips/js/contactChipsDirective.js [hunk 1]
```diff
@@ -63,6 +65,8 @@ var MD_CONTACT_CHIPS_TEMPLATE = '\
               md-items="item in $mdContactChipsCtrl.queryContact($mdContactChipsCtrl.searchText)"\
               md-item-text="$mdContactChipsCtrl.itemName(item)"\
               md-no-cache="true"\
+              md-min-length="$mdContactChipsCtrl.minLength"\
+              md-has-not-found="true"\
```
Comment (topherfangio) [inline src/components/chips/js/contactChipsDirective.js]: Sorry for the delay; Thomas and I have both been traveling a bit.

Can you describe the necessity of the `md-has-not-found` here since it is automatically added if we see the associated template?

Comment (lievenjanssen) [inline src/components/chips/js/contactChipsDirective.js]: When I don't set the `md-has-not-found` attribute the search function is not called when `md-min-length` equals 0. I noticed that it was also set to true on the first `md-autocomplete` demo. If it's better to fix this in another way can you point me in the right direction?

Comment (lievenjanssen) [inline src/components/chips/js/contactChipsDirective.js]: @topherfangio while doing further research I found a bug on the master branch that isn't in the v1.1.0-rc5 release. When I remove the `md-not-found` element in the basic `md-autocomplete` example I would expect that the search function would still work since the `md-min-length` equals 0. This is however not the case on anymore on the master branch while seems to work in the v1.1.0-rc5 release.

I'm doing some further research.

Comment (DevVersion) [inline src/components/chips/js/contactChipsDirective.js]: @lievenjanssen This is a valid and known bug. We are going to fix this with #9291 (hopefully)

Comment (lievenjanssen) [inline src/components/chips/js/contactChipsDirective.js]: @DevVersion @topherfangio I removed the md-has-not-found attribute. This PR is dependent on merge of #9291.

**Comment by lievenjanssen** [comment]
@DevVersion will this PR be merged together with #9291 and is the milestone still 1.1.1?

**Comment by DevVersion** [comment]
@lievenjanssen I hope so - still waiting for @topherfangio's manual testing of #9291.

File: src/components/chips/js/contactChipsDirective.js (hunk 1 above)
Comment (topherfangio) [inline src/components/chips/js/contactChipsDirective.js]: Still waiting on #9291 to be merged.

@lievenjanssen Can you ping me in a few days if it doesn't get merged so I remember to bring it back up?

Comment (lievenjanssen) [inline src/components/chips/js/contactChipsDirective.js]: @topherfangio a ping as requested ;-) #9291 is merged in the meantime.

**Comment by ThomasBurleson** [comment]
@lievenjanssen  please provide 1 or more unit tests.

**Comment by lievenjanssen** [comment]
@ThomasBurleson I added a test to check if minLength on autocomplete controller equals md-min-length attribute on md-contact-chips element.

File: src/components/chips/contact-chips.spec.js [hunk 2]
```diff
@@ -82,6 +83,15 @@ describe('<md-contact-chips>', function() {
         expect(chip.find('img').length).toBe(0);
     });
 
+    it('check if minLength on autocomplete controller equals md-min-length attribute on md-contact-chips element', inject(function() {
```
Comment (DevVersion) [inline src/components/chips/contact-chips.spec.js]: Can we rename this to `should forward md-min-length attribute to the autocomplete` ?

Comment (DevVersion) [inline src/components/chips/contact-chips.spec.js]: Can we rename this to `should forward md-min-length attribute to the autocomplete` ?

Comment (lievenjanssen) [inline src/components/chips/contact-chips.spec.js]: Done

**Comment by lievenjanssen** [comment]
Am I correct that the presubmit prerequisite (https://github.com/angular/material/pull/9291) is fulfilled and that this can be merged?
