### PR TITLE
fix(input): remove unnecessary warnings when ng-messages not provided

### LINKED ISSUE #10461: input: ng-messages animation errors
screen shot 2017-03-06 at 3 44 25 pm

screen shot 2017-03-06 at 3 44 11 pm

Visible with ng 1.5.x and 1.6.x

### PR DESCRIPTION
**Pull request by marosoft**
There is no requirement to include the messages in case of an error.
Highlighting the field can be enough.

Fixes #10461

## PR Checklist
Please check that your PR fulfills the following requirements:
- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [ ] Tests for the changes have been added or this is not a bug fix / enhancement
- [x] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
At the moment warning are displayed in the console when ng-messages are not specified for the input field.

Issue Number:
Relates to #10461 
Relates to #9468

## What is the new behavior?
The warnings are not generated as it is not required to include the error messages.
The original fix for #9468 is still in place. The other changes introduced together with that fix were removed.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: src/components/input/input.js [hunk 1]
```diff
@@ -1007,15 +1005,8 @@ function ngMessageAnimation($$AnimateRunner, $animateCss, $mdUtil, $log) {
 function showInputMessages(element, done) {
   var animators = [], animator;
   var messages = getMessagesElement(element);
-  var children = messages.children();
-
-  if (messages.length == 0 || children.length == 0) {
-    $log.warn('mdInput messages show animation called on invalid messages element: ', element);
-    done();
-    return;
-  }
```
Comment (Splaktar) [inline src/components/input/input.js]: I can understand removing the warning, but this seems to also be removing the `done();` call and the early `return`. I think that we still want those things for performance and correctness. We don't need to trigger the animations if there are no messages to animate in.

File: src/components/input/input.js [hunk 2]
```diff
@@ -1027,15 +1018,8 @@ function showInputMessages(element, done) {
 function hideInputMessages(element, done) {
   var animators = [], animator;
   var messages = getMessagesElement(element);
-  var children = messages.children();
-
-  if (messages.length == 0 || children.length == 0) {
-    $log.warn('mdInput messages hide animation called on invalid messages element: ', element);
-    done();
-    return;
-  }
```
Comment (Splaktar) [inline src/components/input/input.js]: Same here. We don't need to animate the messages out if there are no messages.

File: src/components/input/input.js (hunk 1 above)
Comment (marosoft) [reply src/components/input/input.js]: This makes sense, thanks. I will implement those changes.

As the `animators` array is empty it should not cause any performance issues. However for the correctness it makes sense to handle it here rather than depend on the behaviour of the called `all` function.

I will fix it as soon as possible.

File: src/components/input/input.js [hunk 3]
```diff
@@ -1007,12 +1005,11 @@ function ngMessageAnimation($$AnimateRunner, $animateCss, $mdUtil, $log) {
 function showInputMessages(element, done) {
   var animators = [], animator;
   var messages = getMessagesElement(element);
-  var children = messages.children();
+  var children = messages.children();
```
Comment (Splaktar) [inline src/components/input/input.js]: Can you please remove the added whitespace at the end of this line?

File: src/components/input/input.js [hunk 4]
```diff
@@ -1027,12 +1024,11 @@ function showInputMessages(element, done) {
 function hideInputMessages(element, done) {
   var animators = [], animator;
   var messages = getMessagesElement(element);
-  var children = messages.children();
+  var children = messages.children();
```
Comment (Splaktar) [inline src/components/input/input.js]: Can you please remove the added whitespace at the end of this line?

**Comment by marosoft** [comment]
@Splaktar just wanted to highlight that I squashed the commits
