### PR TITLE
fix(checkbox): enter submits form when submit button is disabled

### LINKED ISSUE #11639: checkbox: should fire click event on submit button if one exists
## Bug

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Focus the native checkbox
1. Press enter and verify that the form was not submitted (validation text doesn't display)
1. Focus the `md-checkbox`
1. Press enter and see that the form was submitted (validation text displays)

Examples of the native behavior
- https://jsbin.com/matuvoj/1/edit?html,js,output
- https://jsbin.com/leforagipo/1/edit?html,js,output

### What is the expected behavior?
When the `ENTER` key is pressed, checkbox should search the form for all submit `button`s and `input`s and send a `MouseClick` event to the first submit button that is not disabled.

Verify that this [CodePen](https://codepen.io/Splaktar/pen/ZVjWRJ?editors=1010#0) still works.

### What is the current behavior?
Checkbox emits a native `submit` event when the `ENTER` key is pressed.

### What is the use-case or motivation for changing an existing behavior?
Checkbox keyboard behavior should match the native behavior on Chrome.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.6
- AngularJS Material: 1.1.13
- OS: macOS
- Browsers: Chrome
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
@codymikol heads up that this is related to PR #11584 and issue https://github.com/angular/material/issues/11583. I will try to make a fix for this today.

### PR DESCRIPTION
**Pull request by Splaktar**
## PR Checklist
Please check that your PR fulfills the following requirements:
- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [x] Tests for the changes have been added or this is not a bug fix / enhancement
- [x] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Checkbox emits a native `submit` event when the `ENTER` key is pressed.

Issue Number: 
Fixes #11639

## What is the new behavior?
- match the behavior of the native input type checkbox
- When the `ENTER` key is pressed, `md-checkbox` searches the `form` for all submit `button`s and `input`s and send a `MouseClick` event to the first one that is enabled.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
I created tests for all of the following use cases
- [x] if there is an enabled `input type="submit"` with a `ng-click` before a `button type="submit"`, verify that the click is fired on the `input`
- [x] if there is an enabled `button type="submit"` with a `ng-click` before a `input type="submit"`, verify that the click is fired on the `button`
- [x] if the form has `ng-submit` and an enabled `input type="submit"`, verify that the form gets submitted
- [x] if the form has `ng-submit` and an enabled `button type="submit"`, verify that the form gets submitted
- [x] if the form has an enabled `input type="submit"` with `ng-click`, verify that the form gets submitted
- [x] if the form has an enabled `button type="submit"` with `ng-click`, verify that the form gets submitted
- [x] Variations where `input type="submit"` and `button type="submit"` are disabled but a second one is enabled and gets the click event
- [x] negative tests where the `input type="submit"` and `button type="submit"` are disabled, verify that the form does not get submitted

### CODE REVIEW

File: src/components/checkbox/checkbox.js [hunk 1]
```diff
@@ -169,19 +169,29 @@ function MdCheckboxDirective(inputDirective, $mdAria, $mdConstant, $mdTheming, $
...
-            // We have to use a native event here as the form directive does not use jqlite
+            // Match the behavior of the native input type="checkbox".
+            // It's important that MouseEvent is used here versus Event in order to match the native
+            // behavior and properly trigger ng-submit.
+            form = $mdUtil.getClosest(ev.target, 'form');
             if (form) {
-              form.dispatchEvent(new Event('submit'));
+              submit = form.querySelector('button[type="submit"]:enabled, input[type="submit"]:enabled');
+              if (submit) {
+                submit.dispatchEvent(new MouseEvent('click'));
```
Comment (jelbourn) [inline src/components/checkbox/checkbox.js]: Why not just call `submit.click()`?

Comment (Splaktar) [reply src/components/checkbox/checkbox.js]: Good call. Done.

File: src/components/checkbox/checkbox.js [hunk 2]
```diff
@@ -169,19 +169,29 @@ function MdCheckboxDirective(inputDirective, $mdAria, $mdConstant, $mdTheming, $
...
+            // Match the behavior of the native input type="checkbox".
+            // It's important that MouseEvent is used here versus Event in order to match the native
+            // behavior and properly trigger ng-submit.
+            form = $mdUtil.getClosest(ev.target, 'form');
             if (form) {
-              form.dispatchEvent(new Event('submit'));
+              submit = form.querySelector('button[type="submit"]:enabled, input[type="submit"]:enabled');
+              if (submit) {
+                submit.click();
+              }
```
Comment (codymikol) [inline src/components/checkbox/checkbox.js]: I would imagine this would work similarly to inputs.
If a submit button is found, fire a click event onto it, otherwise just submit the form.

This behavior is currently present on inputs: [Code Pen](https://codepen.io/codymikol/pen/OdaQYy?editors=1010#0)

I leverage this kind of behavior in my application. In some circumstances I have an outer controller that doesn't know about it's contents, but has the ability to fire submit events to child forms via a directive. I also want the user to be able to use the keyboard inside of the form to submit.

There is an attribute "form" which allows you to specify the form for a submit button outside of a form, but it is not supported in IE 11.

File: src/components/checkbox/checkbox.spec.js [hunk 3]
```diff
@@ -298,14 +298,14 @@ describe('mdCheckbox', function() {
...
+    it('should not submit a parent form when ENTER is pressed', function () {
       var form = compileAndLink('<form><md-checkbox ng-checked="value"></md-checkbox></form>');
       angular.element(form[0].getElementsByTagName('md-checkbox')[0]).triggerHandler({
         type: 'keypress',
         keyCode: $mdConstant.KEY_CODE.ENTER
       });
       pageScope.$apply();
-      expect(form[0].classList.contains('ng-submitted')).toBe(true);
+      expect(form[0].classList.contains('ng-submitted')).toBe(false);
     });
```
Comment (codymikol) [inline src/components/checkbox/checkbox.spec.js]: You might want to add a test to prove that a checkbox is submitted when expected as well.

File: src/components/checkbox/checkbox.js (hunk 2 above)
Comment (codymikol) [reply src/components/checkbox/checkbox.js]: I do see that there is definitely native inconsistency with this. Inputs will submit regardless of submit button presence, but checkboxes require one. However, I don't see any drawback to allowing this kind of behavior in absence of a submit button.

Comment (Splaktar) [reply src/components/checkbox/checkbox.js]: Well the primary thing that we have to fix is that `Enter` on checkboxes should not submit the form if the submit button/input is disabled.

I forked your [CodePen](https://codepen.io/Splaktar/pen/NooaYZ?editors=1010#0) and added a native `input`. It submits on `Enter` without a submit button/input *only* if it's the only input in the form. If there are 2 `inputs`, the `Enter` key does not submit without a submit button/input.

Some of this odd behavior is captured in the [AngularJS Form Directive docs](https://docs.angularjs.org/api/ng/directive/form#submitting-a-form-and-preventing-the-default-action).

I suppose we could theoretically submit the form on `Enter` for a checkbox if no submit button or input is found, but is inconsistent with [native behavior](https://jsbin.com/lajutej/edit?html,js,output). So it's likely not a good idea. If you comment out the input in this JSBin, `Enter` on a lone `checkbox` does not submit the form.

File: src/components/checkbox/checkbox.js [hunk 4]
```diff
@@ -169,19 +169,29 @@ function MdCheckboxDirective(inputDirective, $mdAria, $mdConstant, $mdTheming, $
...
           case $mdConstant.KEY_CODE.SPACE:
             element.addClass('md-focused');
             listener(ev);
             break;
           case $mdConstant.KEY_CODE.ENTER:
-            var form = $mdUtil.getClosest(ev.target, 'form');
-            // We have to use a native event here as the form directive does not use jqlite
+            // Match the behavior of the native input type="checkbox".
+            // It's important that MouseEvent is used here versus Event in order to match the native
+            // behavior and properly trigger ng-submit.
```
Comment (jelbourn) [inline src/components/checkbox/checkbox.js]: I think the `Event` part of this comment is no longer necessary. I would, however, expand the comment like:
```ts
// Match the behavior of the native <input type="checkbox">.
// When the enter key is pressed while focusing a native checkbox
// inside a form, the browser will trigger a `click` on the first non-disabled
// submit button in the form. Note that this is different from text inputs, which
// will directly submit the form without needing a submit button to be present.
```

File: src/components/checkbox/checkbox.spec.js [hunk 5]
```diff
@@ -298,15 +299,137 @@ describe('mdCheckbox', function() {
       expect(isChecked(checkbox)).toBe(false);
     });
 
-    it('should submit a parent form when ENTER is pressed', function () {
-      var form = compileAndLink('<form><md-checkbox ng-checked="value"></md-checkbox></form>');
-      angular.element(form[0].getElementsByTagName('md-checkbox')[0]).triggerHandler({
-        type: 'keypress',
-        keyCode: $mdConstant.KEY_CODE.ENTER
+    it('should not submit a parent form when ENTER is pressed and there is no submit button/input',
```
Comment (jelbourn) [inline src/components/checkbox/checkbox.spec.js]: There should also be a case that tests that the checkbox triggers the *first* non-disabled submit button when there are multiple.

Comment (Splaktar) [reply src/components/checkbox/checkbox.spec.js]: Added.

File: src/components/checkbox/checkbox.js (hunk 4 above)
Comment (Splaktar) [reply src/components/checkbox/checkbox.js]: Good catch, updated.
