### PR TITLE
fix(icon): SVG elements are not loaded from the cache properly on IE11

### LINKED ISSUE #11603: icon: SVG icons disappear in IE11 when reused from internal cache
## Bug, enhancement request, or proposal:
Since commit https://github.com/angular/material/commit/47527f245acc8382a69a42a07989fd5f646e9744 SVG icons which are reused from the cache (md-icons internal one) are not displayed anymore in IE11 because `transformClone` removes the `<svg>`-element and adds only the children to the dom (see https://github.com/angular/material/commit/47527f245acc8382a69a42a07989fd5f646e9744#diff-8a475bebd83d2830320cb84bceeade2cR505)

# CodePen and steps to reproduce the issue:
Just go to the docs (https://material.angularjs.org/latest/demo/icon) with IE11. Initially the SVG on the "Edit on Codepen"- and "View Source"-buttons will be visible. Click on a different demo and they will be invisible. 

### Which versions of AngularJS, Material, OS, and browsers are affected?
- AngularJS: 1.7.6 
- AngularJS Material: 1.1.11 and 1.1.12
- OS: Windows
- Browsers: IE11

### PR DESCRIPTION
**Pull request by Splaktar**
## PR Checklist
Please check that your PR fulfills the following requirements:
- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [ ] Tests for the changes have been added or this is not a bug fix / enhancement
- [x] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
SVG elements are not loaded from the cache properly on IE11. The outer `<svg>` tag is lost.

Issue Number: 
Fixes #11603. Relates to #11545. Closes #11604.

## What is the new behavior?
SVG elements are loaded from the cache properly on IE11 including the `<svg>` tag and the element's attributes.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
We can't just use `outerHTML` here either due to that [not being supported for SVG elements in IE](https://stackoverflow.com/questions/29888050/outerhtml-is-not-working-in-ie) as well.

### CODE REVIEW

File: src/core/util/util.js [hunk 1]
```diff
@@ -874,6 +874,16 @@ function UtilFactory($document, $timeout, $compile, $rootScope, $$mdAnimate, $in
...
         return serializer.serializeToString(child);
       }).join('');
+    },
+
+    /**
+     * Function to get outerHTML of SVG and Symbol elements in IE11
+     * @param {Element} element
+     * @returns {string} the outerHTML of the element passed in
+     */
+    getOuterHTML: function(element) {
```
Comment (jelbourn) [inline src/core/util/util.js]: Why not just use the `outerHTML` property?
https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML

Comment (Splaktar) [reply src/core/util/util.js]: It's not supported by IE11 for SVG elements. It returns `undefined`.

Comment (Splaktar) [reply src/core/util/util.js]: It's not mentioned in https://caniuse.com/#feat=xml-serializer, but I've left feedback that it should be added to the Known Issues.

Comment (Splaktar) [reply src/core/util/util.js]: Reference: https://stackoverflow.com/questions/29888050/outerhtml-is-not-working-in-ie.
Also manually tested.

Comment (jelbourn) [reply src/core/util/util.js]: Got it. I would just add an line comment here that adds all of that context to the code. The function description should just be `Gets the outer HTML content of the given HTMLElement`
