### PR TITLE
fix(autocomplete): improve implementation of aria-activedescendant

### LINKED ISSUE #11742: autocomplete: results are not voiced with index information
## Bug, enhancement request, or proposal:
The AngularJS Material Autocomplete component does not announce the index of results (e.g., "1 of 3") to screen readers.

# Steps to reproduce the issue:
Issue can be reproduced on https://material.angularjs.org/HEAD/demo/autocomplete

#### Detailed Reproduction Steps: 
1. Turn on ChromeVox
1. Go to https://material.angularjs.org/HEAD/demo/autocomplete
1. Enter 'al' into the 'Favorite State' autocompleter and let the results load
1. Use the keyboard's arrow keys to move focus to 'Alaska'
1. Note that 'Alaska, Status' is voiced

### What is the expected behavior?
1. 'Alaska, List item, 2 of 2'

### What is the current behavior?
1. 'Alaska, Status'

### What is the use-case or motivation for changing an existing behavior?
Accessibility.  Screen reader users need to know how many items are loaded and what the current position of the focus is.

### Which versions of AngularJS, Material, OS, and browsers are affected?
- AngularJS: 1.6
- AngularJS Material: 1.1.19
- OS: ChromeOS and GNU/Linux
- Browsers: Chrome
- Screen readers: ChromeVox, VoiceOver and JAWS
 
#### Working examples:
The desired behavior can be observed in the Angular Material library.  See the demos at https://material.angular.io/components/autocomplete/examples

It can also be observed in the w3.org examples, such as https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html

### PR DESCRIPTION
**Pull request by Splaktar**
## PR Checklist
Please check that your PR fulfills the following requirements:
- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [ ] Tests for the changes have been added or this is not a bug fix / enhancement
- [x] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
ChromeVox announces the following when the user changes to the `Alaska` option
> 'Alaska, Status'

When it should announce something like
> 'Alaska, List item, 2 of 50. ... List box with 8 items.'

Issue Number: 
Fixes #11742

## What is the new behavior?
- allow screen readers to do more and us to do less
  - remove extra calls to announce the item that is visually focused
  - remove tests for these extra live announcements
  - give every option an id for use with `aria-activedescendant`
  - use the `selected` class for styling and finding the active option
- implement recommendations from a11y guides
  - add the clear button to the tab order
  - change input type to `text`
  - always define a `name` attribute
- when the popup isn't expanded
  - `aria-owns` and `aria-activedescendant` shouldn't be defined
- when the autocomplete is disabled
  - `aria-autocomplete` and `aria-role` shouldn't be defined
  - `aria-haspopup` should be false
- add `md-autocomplete-suggestion` class for styling instead of using `li`
- add `md-autoselect` to the dialog demo for help w/ manual testing
- remove overly verbose `aria-describedby` from basic demo
- mark `md-icons` in `md-item-templates` of autocomplete demos as hidden

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
- [x] Verified on VoiceOver for macOS
- [x] Verified on ChromeVox on Chrome OS
- [x] Verified on NVDA for Windows

Related resources
- https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search
- http://web-accessibility.carnegiemuseums.org/code/search/
- https://www.slideshare.net/maxdesign/building-an-accessible-autocomplete

Live demo:
https://angularjs-material.firebaseapp.com/demo/autocomplete

### CODE REVIEW

**Comment by Splaktar** [comment]
There are some e2e failures in g3 due to certain DOM lookups no longer returning results. It may be due to the change to `#selected_option`.

There are also other unit test failures that need to be investigated.

I can probably mitigate these issues once they are more clearly defined and communicated.

**Comment by Splaktar** [comment]
Rebased.

**Comment by Splaktar** [comment]
I've redeployed these changes to https://angularjs-material.firebaseapp.com/demo/autocomplete. I had recently deployed some `md-select` a11y changes to that site for ChromeVox testing.

File: src/components/autocomplete/js/autocompleteDirective.js [hunk 1]
```diff
@@ -500,20 +500,20 @@ function MdAutocomplete ($$mdSvgRegistry) {
...
-                aria-owns="ul-{{$mdAutocompleteCtrl.id}}"\
-                ng-attr-aria-activedescendant="{{$mdAutocompleteCtrl.index >= 0 ? \'selected_option\' : undefined}}">\
+                ng-attr-aria-owns="{{$mdAutocompleteCtrl.hidden || $mdAutocompleteCtrl.isDisabled ? undefined : \'ul-\' + $mdAutocompleteCtrl.id}}"\
+                ng-attr-aria-activedescendant="{{!$mdAutocompleteCtrl.hidden && $mdAutocompleteCtrl.activeOption ? $mdAutocompleteCtrl.activeOption : undefined}}">\
               <div md-autocomplete-parent-scope md-autocomplete-replace>' + leftover + '</div>\
             </md-input-container>';
         } else {
           return '\
-            <input type="search"\
+            <input type="text"\
```
Comment (Splaktar) [inline src/components/autocomplete/js/autocompleteDirective.js]: This appears to be breaking some custom styles within g3. They are likely targeting `input[type="search"]` to apply their custom search box styling.

Comment (Splaktar) [reply src/components/autocomplete/js/autocompleteDirective.js]: It's probably best if they use the `md-input-class` API to set a class for custom styling instead.

**Comment by Splaktar** [comment]
Received feedback on this based on JAWS testing that scrolling of the options list should wrap. Opened https://github.com/angular/material/issues/11766 to track that issue separate from this PR.

**Comment by Splaktar** [comment]
Received feedback on this based on JAWS testing that the default Escape key behavior did not align with expectations. Noted that we do have the `md-escape-options` API to change this behavior. Opened https://github.com/angular/material/issues/11767 to consider changing the default Escape handling to align with the [WAI-ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html).

**Comment by Splaktar** [comment]
It looks like the remaining presubmit issues can be handled within g3, then this will be able to get merged.

File: src/components/autocomplete/autocomplete.scss [hunk 2]
```diff
@@ -214,7 +214,7 @@ md-autocomplete {
   list-style: none;
   padding: 0;
 
-  li {
+  .md-autocomplete-suggestion {
```
Comment (norkunas) [inline src/components/autocomplete/autocomplete.scss]: These styles are not applied anymore to <md-not-found> item element which is converted to "li".
You can see this in the first autocomplete demo https://material.angularjs.org/latest/demo/autocomplete

Comment (Splaktar) [reply src/components/autocomplete/autocomplete.scss]: You can see these styles applied in this screenshot using that demo:
Screen Shot 2020-01-30 at 10 21 01

Comment (norkunas) [reply src/components/autocomplete/autocomplete.scss]: Yeah, but enter some query which doesn't match any results and you'll see that not-found template is not styled anymore.

Comment (Splaktar) [reply src/components/autocomplete/autocomplete.scss]: OK, thank you for the updated reproduction steps. I've opened https://github.com/angular/material/issues/11852 to track this.

Comment (norkunas) [reply src/components/autocomplete/autocomplete.scss]: Thanks for opening issue :)
