### PR TITLE
fix(menu): close menu on tab

### LINKED ISSUE #11123: menu: should close when pressing tab
Currently, when you tab from an open menu it moves through the items and then escapes the panel into the rest of the page. The menu should actually just close upon pressing tab and the focus should move to the next focusable element (the menu items shouldn't be tab stops). `MatMenu` does the right thing for this and can be an example.

### PR DESCRIPTION
**Pull request by Splaktar**
## PR Checklist
Please check that your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Pressing tab inside of a menu panel (`md-menu-content`) can cause the focus to escape the panel and move to other parts of the page (with the menu panel still open).

Issue Number: 
Fixes #11123

## What is the new behavior?
Use only arrow keys to navigate menus (not tabs).
Resolve issue where tab can escape the panel by closing the menu when the `TAB` keyCode is detected.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
N/A

### CODE REVIEW

File: src/components/menu/js/menuServiceProvider.js [hunk 1]
```diff
@@ -289,6 +289,7 @@ function MenuProvider($$interimElementProvider) {
           var handled;
           switch (ev.keyCode) {
             case $mdConstant.KEY_CODE.ESCAPE:
+            case $mdConstant.KEY_CODE.TAB:
               opts.mdMenuCtrl.close(false, { closeAll: true });
               handled = true;
```
Comment (crisbeto) [inline src/components/menu/js/menuServiceProvider.js]: Looking at the logic below, when an event is marked as `handled`, it'll prevent the default action. This shouldn't be the case `TAB`, because it'll prevent people from moving forward.

Comment (jelbourn) [reply src/components/menu/js/menuServiceProvider.js]: Yeah, good catch.

**Comment by Splaktar** [comment]
Feedback addressed. Ready for presubmit.

File: src/components/menu/js/menuServiceProvider.js [hunk 2]
```diff
@@ -292,6 +292,10 @@ function MenuProvider($$interimElementProvider) {
...
               break;
+            case $mdConstant.KEY_CODE.TAB:
+              opts.mdMenuCtrl.close(false, { closeAll: true });
+              handled = false;
```
Comment (jelbourn) [inline src/components/menu/js/menuServiceProvider.js]: Add comment that explains why `handled = false` here.

Comment (Splaktar) [reply src/components/menu/js/menuServiceProvider.js]: Done.
