### PR TITLE
fix(rtl): support applying dir="rtl" on DOM elements other than the body

### LINKED ISSUE #9754: virtual-repeat: horizontal does not work with RTL
**Actual Behavior**:
-  `What is the issue? *`
  The viewport does not get updated when scrolled. We get blank entries
-  `What is the expected behavior?`
  The scrolled elements should show up in the viewport

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`
  http://codepen.io/david-gang/pen/vXpGXA
-  `Details:`
  Just add the tag dir="rtl"

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.1

**Additional Information**:
-  `Browser Type: *` firefox
-  `Browser Version: *` 47.0.1
-  `OS: *`
-  `Stack Traces:`
## This also happens in ie11

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

### LINKED ISSUE #11016: feat: support applying dir="rtl" on DOM elements other than the body
**Actual Behavior**:
 -  I got an issue with the md-tabs with direction RTL. When the list of tabs is too long and the next/previous button are disabled. 
 -  I would expect to have the next/previous buttons enable when it's needed.

**CodePen** (or steps to reproduce the issue): *
 -  https://codepen.io/anon/pen/BmegyY
 -  Resize your browser and see when the buttons next/previous appear

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:` 1.1.5

**Additional Information**:
 -  Browser Type: All
 -  Browser Version: All

### PR DESCRIPTION
**Pull request by marosoft**
Create a single function to check text direction based on dir attribute on DOM element or document.

Fixes #11016 Fixes #9754

## PR Checklist
Please check that your PR fulfills the following requirements:
- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [ ] Tests for the changes have been added or this is not a bug fix / enhancement
- [ ] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[x] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

A whole document is expected to be set as RTL even when a `dir` attribute is set properly on an individual element.
Issue Number: #11016, #9754

## What is the new behavior?
It is possible to use `dir` attribute on an element to override a document's `dir` value.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: src/core/util/util.js [hunk 1]
```diff
@@ -83,12 +83,26 @@ function UtilFactory($document, $timeout, $compile, $rootScope, $$mdAnimate, $in
...
+
+      switch (dir) {
+        case 'ltr':
+          return false;
+        
+        case 'rtl':
+          return true;
+      }
+      
+      return ($document[0].dir == 'rtl' || $document[0].body.dir == 'rtl');
```
Comment (Splaktar) [inline src/core/util/util.js]: Please use `===` here.

File: src/core/util/util.js [hunk 2]
```diff
@@ -83,12 +83,26 @@ function UtilFactory($document, $timeout, $compile, $rootScope, $$mdAnimate, $in
...
+    },
+
     /**
      * Bi-directional accessor/mutator used to easily update an element's
      * property based on the current 'dir'ectional value.
      */
-    bidi : function(element, property, lValue, rValue) {
-      var ltr = !($document[0].dir == 'rtl' || $document[0].body.dir == 'rtl');
+    bidi: function(element, property, lValue, rValue) {
```
Comment (Splaktar) [inline src/core/util/util.js]: Is this still used anywhere after the changes in this PR?

**Comment by Splaktar** [comment]
@marosoft can you please rebase this PR and address the review comments when you get a chance?

File: src/components/virtualRepeat/virtual-repeater.js [hunk 3]
```diff
@@ -385,13 +387,12 @@ VirtualRepeatContainerController.prototype.resetScroll = function() {
...
 VirtualRepeatContainerController.prototype.handleScroll_ = function() {
-  var ltr = document.dir !== 'rtl' && document.body.dir !== 'rtl';
-  if(!ltr && !this.maxSize) {
+  if(!this.ltr && !this.maxSize) {
     this.scroller.scrollLeft = this.scrollSize;
     this.maxSize = this.scroller.scrollLeft;
   }
   var offset = this.isHorizontal() ?
-      (ltr?this.scroller.scrollLeft : this.maxSize - this.scroller.scrollLeft)
+      (this.ltr?this.scroller.scrollLeft : this.maxSize - this.scroller.scrollLeft)
```
[the remark this answers is not in the document]
Comment (marosoft) [reply src/components/virtualRepeat/virtual-repeater.js]: I missed that as well. Changed.

File: src/core/util/util.js [hunk 4]
```diff
@@ -83,12 +83,26 @@ function UtilFactory($document, $timeout, $compile, $rootScope, $$mdAnimate, $in
       return $options.getOption ? $options.getOption(optionName) : $options[optionName];
     },
 
+    isRtl: function(attrs) {
```
[the remark this answers is not in the document]
Comment (marosoft) [reply src/core/util/util.js]: I added it. Please review.

File: src/core/util/util.js (hunk 1 above)
Comment (marosoft) [reply src/core/util/util.js]: Done.

File: src/core/util/util.js (hunk 2 above)
Comment (marosoft) [reply src/core/util/util.js]: Yes, it is used three times in `sticky` component for CSS transformations [here](https://github.com/marosoft/material/blob/wip/rtl-unification/src/components/sticky/sticky.js)

**Comment by marosoft** [comment]
@Splaktar I noticed that `bidi` is mentioned in the [Migration Guide](https://github.com/angular/material/blob/master/docs/content/migration.md).
In the util.js [file](https://github.com/marosoft/material/blob/wip/rtl-unification/src/core/util/util.js#L94) there are three methods related: `isRtl`, `bidi` and `bidiProperty`.

File: src/core/util/util.js [hunk 5]
```diff
@@ -83,12 +83,34 @@ function UtilFactory($document, $timeout, $compile, $rootScope, $$mdAnimate, $in
       return $options.getOption ? $options.getOption(optionName) : $options[optionName];
     },
 
+    /**
+     * Determines the current 'dir'ectional value based on the value of 'dir'
+     * attribute of the element. If that is not defined, it will try to use
+     * a 'dir' attribute of the body or html tag.
+     *
+     * @param $attrs
+     * @returns {boolean}
```
Comment (Splaktar) [inline src/core/util/util.js]:
```suggestion
     * @returns {boolean} true if the element's passed in attributes, the document, or the body indicates RTL mode, false otherwise.
```

**Comment by marosoft** [comment]
> I suggested some improvements to the JSDoc.
> 
> Thanks for the notes for the Migration guide. Would you be interested in adding those to the guide in another PR after this one gets merged?

I made the suggested changes, thanks for those.
I can add the notes to the guide. Do I need to create an issue for that or can I reference any existing one?

**Comment by Splaktar** [comment]
No issue needed. Please just reference this PR. Thank you!

**Comment by marosoft** [comment]
@Splaktar I found this issue which I might use as a reference for the documentation: #8615

I might find some time over the weekend to add some basic unit tests. Do you want me to add those for each component impacted by the change together with the changes I made to `util.js` ?

**Comment by Splaktar** [comment]
Ideally, it would be nice to see a couple tests for each affected component (in their `spec.js` files) and then some more general tests in `util.spec.js`. It would help us make sure that this functionality kept working over the long term.

Affected components
- menu
- panel
- slider
- sticky
- tabs
- grid-list
- virtual-repeat

Good catch on that RTL docs issue!
