### PR TITLE
fix(icon): large SVG files can cause icon caching to hang

### LINKED ISSUE #11651: icon(svg): large icon from cache causes 100% CPU during RegEx replacement
## Bug

Since AngularJS Material version 1.1.11,
The site is stuck after the second opening of the dialog with the SVG icons

# CodePen and steps to reproduce the issue:
[CodePen](https://codepen.io/gal-koren/pen/WPVbgr?editors=1010)
1)Click on "CUSTOM DIALOG" button.
2)Close the dialog
3)Click again on the  "CUSTOM DIALOG" button.
4)Chrome stuck.

When I debug it I saw that the code is stuck on this function "transformClone".

issue: Chrome 

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.7
- AngularJS Material:  1.1.13 , 1.1.12 , 1.1.11 
- OS: Windows
- Browsers: all

Thanks :)

### PR DESCRIPTION
**Pull request by Splaktar**
## PR Checklist
Please check that your PR fulfills the following requirements:
- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [ ] Tests for the changes have been added or this is not a bug fix / enhancement
- [x] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Large SVGs (170KB+) can cause the current caching RegEx code to hang and use 100% CPU for a long amount of time, freezing the app.

Issue Number:
Fixes #11651. Relates to #8689. Relates to #11342. Relates to #11635.

## What is the new behavior?
No more hangs processing large cached SVGs
- use querySelectorAll as much as possible
- reduce the use of RegEx on large chunks of DOM

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
The reporter added a demo full of various SVGs in a dialog. I [verified that these changes](https://github.com/angular/material/pull/11653) fix all of those SVGs.

### CODE REVIEW

File: src/components/icon/js/iconService.js [hunk 1]
```diff
@@ -495,27 +500,69 @@ function MdIconService(config, $templateRequest, $q, $log, $mdUtil, $sce) {
...
+
+    // Verify that the newUid only contains a number and not some XSS content.
+    if (!isFinite(Number(newUid))) {
+      throw new Error('Unsafe and unexpected non-number result for newUid.');
+    }
+    cacheSuffix = '_cache' + newUid;
+
+    // outerHTML of SVG elements is not supported by IE11
+    if (isIeSvg) {
+      // TODO this needs to be verified in IE11 manually
```
Comment (Splaktar) [inline src/components/icon/js/iconService.js]: - [ ] Need to verify against IE11

**Comment by Splaktar** [comment]
I've finished my testing on IE11. 

I had to tweak it to use `referencingElement.textContent = angular.element(svgElement)[0].innerHTML;` instead of `referencingElement= angular.element(svgElement)[0];` as this wasn't updating the DOM.

There seem to be some other issues, possibly SVGs that don't well support IE11, with 5 of the supplied SVGs in the CodePen above. The first time that many of them are displayed in IE11, they are black silhouettes. The second time when loaded from the cache (after this fix), they render properly with their full textures and colors.  I compared the SVG structure in the DOM and there were no changes before/after that would explain this behavior.

I tested this with [1.1.10](https://codepen.io/Splaktar/pen/XGXpyz?editors=1010) and the same images were black. However, the second time they are displayed, they remained black.

So as far as I can tell, `md-icon` SVG support in IE11 will be improved by this change 😄
