### PR TITLE
docs: Fix many links and other issues.

### LINKED ISSUE #9352: docs: some links leads to 404
There is some links leading to 404 on 1.1.0 docs.

I only found these:
- Link from [\<md-subheader\> directive](https://material.angularjs.org/1.1.0/api/directive/mdSubheader) to `$mdSticky`.
- Links from [\<md-autocomplete\> directive (https://material.angularjs.org/1.1.0/api/directive/mdAutocomplete) to `VirtualRepeat` and `VirtualRepeatContainer`.

I can see it's only happening with internal links.

### PR DESCRIPTION
**Pull request by topherfangio**
There are a few places in the docs that point to `/something/somewhere` which works on localhost, but fails on the live site because the live site adds `/latest` or `/HEAD` to the URL.

 - **Update**: Absolute links to be relative.
 - **Update**: Material Design links to use new url (material.goole.com) to
   avoid redirects (and potentially broken links in the future).

Additionally, fix a few bugs with some of our doc-specific code.

 - **Fix**: Null pointer exception when sidenav is closed (i.e. on mobile).
 - **Fix**: `<hljs>` code snippets removed useful whitespace.

Additionally, update the Getting Started page with formatting/styling improvements and new links.

 - **Update**: Formatting/styling/extra tags.
 - **New**: Add new links for Material Start.
 - **Fix**: Link titles all say `Link opens in a new window`.

Finally, fix various typos/formatting issues including (but not limited to):

 - **Update**: Notes should look the same across pages.
 - **Fix**: Incorrect markdown support in panel docs.
 - **Update**: Add `<hljs>` snippet formatting to panel docs.
 - **New**: Add description to `$mdAriaProvider.disableWarnings()` method.

   This was mainly because it visually looked odd not to have one.

Fixes #9352.

Ping @ThomasBurleson @EladBezalel for general review and @ErinCoughlan for panel review.

### CODE REVIEW

File: src/components/autocomplete/js/autocompleteDirective.js [hunk 1]
```diff
@@ -35,10 +35,10 @@ angular
  * There is an example below of how this should look.
  *
  * ### Notes
- * The `md-autocomplete` uses the the [VirtualRepeat](/api/directive/mdVirtualRepeatContainer)
+ * The `md-autocomplete` uses the the [VirtualRepeat](api/directive/mdVirtualRepeat)
```
Comment (DevVersion) [inline src/components/autocomplete/js/autocompleteDirective.js]: This is intentionally linked to the `mdVirtualRepeatContainer`. 
> The label was just Virtual Repeat because the container is actually the over-all component.

Comment (topherfangio) [inline src/components/autocomplete/js/autocompleteDirective.js]: Ok, well I added links on both the VirtualRepeat and the VirtualRepeatContainer to easily jump between them.

I think seeing the docs for the VirtualRepeat is more useful than the container?

Comment (DevVersion) [inline src/components/autocomplete/js/autocompleteDirective.js]: The `virtual-repeat` directive itself does actually not contain any useful information about the way it works.

I intentionally linked to the `VirtualRepeatContainer`, because it is responsible for handling all the repeated blocks and includes all insight information.

The most important reason, is just to link to the Virtual Repeat container because of the common issues like https://github.com/angular/material/issues/9126.

I know it's linked below as well - but this is just to make the developer explicitly aware of the Virtual Repeat Container when submitting new issues regarding the dropdown.

> We can keep it as it is, just wanted to clarify why I linked it to the container instead.

File: docs/app/partials/getting-started.tmpl.html [hunk 2]
```diff
@@ -1,87 +1,123 @@
...
+        <a href="https://github.com/angular/material-start/tree/master" target="_blank"
+           title="Material-Start - ES5">Learn with Material-Start: Completed (es5)</a>
+      </li>
+
+      <li>
+        <a href="http://codepen.io/team/AngularMaterial/pen/RrbXyW" target="_blank">Start with a
+        blank CodePen Material Application</a>
+      </li>
+
+      <li style="margin-bottom: 30px;">
```
Comment (EladBezalel) [inline docs/app/partials/getting-started.tmpl.html]: maybe a class? (i don't like inline styles)

**Comment by EladBezalel** [comment]
This looks good ! :+1:

**Comment by ThomasBurleson** [comment]
Gatekeeper - LGTM
