### PR TITLE
fix(chips): improve ability to receive focus on click

### LINKED ISSUE #10344: chips: regression to component focus in 1.1.2
**Actual Behavior**:
 -  `md-chips focus is being applied only inside md-chip-input-container`
 -  `Focus should be there through out the md-chips`

**Angular Versions**: *
 -  `Angular Material Version:1.1.3`

### PR DESCRIPTION
**Pull request by Splaktar**
## PR Checklist
Please check that your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Clicking at the end of `md-chips` or between `md-chip`s no longer focuses the chips input after 1.1.2. Many developers have complained that this creates poor UX and that their users have complained.

Issue Number: 
#10344

## What is the new behavior?
Clicking at the end of `md-chips` or between `md-chip`s focuses the chips input.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This solves a regression introduced in 1.1.2.

Fixes #10344

### CODE REVIEW

File: src/components/chips/js/chipsDirective.js [hunk 1]
```diff
@@ -199,7 +199,7 @@
               role="option"\
               aria-selected="{{$mdChipsCtrl.selectedChip == $index}}" \
               aria-posinset="{{$index}}"\
-              ng-click="!$mdChipsCtrl.readonly && $mdChipsCtrl.focusChip($index)"\
+              ng-click="!$mdChipsCtrl.readonly && $mdChipsCtrl.focusChip($index, $event)"\
```
Comment (DevVersion) [inline src/components/chips/js/chipsDirective.js]: I'm kind of worried about stopping propagation here. Can't you below in the other `click` event just check if a chip or the input is selected?

Right now, it seems like it also resets the selected item on every input element click.

**Comment by Splaktar** [comment]
Look at fixing https://github.com/angular/material/issues/10758 as part of this as well.

File: src/components/chips/js/chipsDirective.js (hunk 1 above)
Comment (Splaktar) [reply src/components/chips/js/chipsDirective.js]: Clearing the selected chip on input focus or md-chips blur seems to be the expected behavior (as it's in 1.1.1, 1.1.9, and HEAD). This is also consistent with Angular Material.

Comment (Splaktar) [reply src/components/chips/js/chipsDirective.js]: Good tip on the check in the directive's click handler. That works well!

**Comment by Splaktar** [comment]
Decided to keep the fix for #10758 separate. PR for that one is open here: https://github.com/angular/material/pull/11305.

**Comment by jelbourn** [comment]
@Splaktar this passes presubmit but has a merge conflict

**Comment by Splaktar** [comment]
Rebase complete.
