### PR TITLE
fix(sidenav): allow for data bindings in md-component-id

### LINKED ISSUE #9052: mdSidenav renders before scope variables are populated
**Actual Behavior**:
 -  `What is the issue? *`

The html below is loaded by a component through the property templateUrl, and the mdSidenav directive is rendered before {{ ::$ctrl.id }} gets evaluated. So the md-component-id becomes literally the string "{{ ::$ctrl.id }}"

&lt;md-sidenav
    class="md-sidenav-left md-whiteframe-2dp"
    md-component-id="{{ ::$ctrl.id }}"
    md-is-locked-open="$mdMedia('gt-sm')"&gt;
        &lt;md-toolbar&gt;
            &lt;h1 class="text-center"&gt;{{ $ctrl.header }}&lt;/h1&gt;
        &lt;/md-toolbar&gt;
        &lt;md-content&gt;
            &lt;menu-dropdown navigation="$ctrl.navigation"&gt;&lt;/menu-dropdown&gt;
        &lt;/md-content&gt;
&lt;/md-sidenav&gt;

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.0.9

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes the sidenav not evaluating expressions inside of the `md-component-id` attribute.

Fixes #9052.

### CODE REVIEW

**Comment by DevVersion** [comment]
I think @EladBezalel had something similar, including observation of the attribute. https://github.com/angular/material/pull/5972

**Comment by crisbeto** [comment]
Seems like it didn't end up getting merged. @EladBezalel is it ok if I incorporate the changes here?

**Comment by crisbeto** [comment]
Updated, although the approach from #5972 doesn't work for cases where the instance is being looked up in a controller on load.

File: src/components/sidenav/sidenav.js [hunk 1]
```diff
@@ -505,5 +503,19 @@ function SidenavController($scope, $element, $attrs, $mdComponentRegistry, $q) {
...
+  // Evaluate the component id.
+  var rawId = $attrs.mdComponentId;
+  var componentId = rawId && rawId.indexOf($interpolate.startSymbol()) > -1 ?
+    $interpolate(rawId)($scope.$parent) : rawId;
+
+  // Register the component.
+  self.destroy = $mdComponentRegistry.register(self, componentId);
+
+  // Watch and update the component, if the id has changed.
+  $attrs.$observe('mdComponentId', function(id) {
```
Comment (ThomasBurleson) [inline src/components/sidenav/sidenav.js]: Should we only do this if we originally had interpolation symbols ?

File: src/components/sidenav/sidenav.js [hunk 2]
```diff
@@ -505,5 +503,19 @@ function SidenavController($scope, $element, $attrs, $mdComponentRegistry, $q) {
...
+    if (id && id !== self.$$mdHandle) {
+      self.destroy();
+      self.destroy = $mdComponentRegistry.register(self, id);
```
Comment (ThomasBurleson) [inline src/components/sidenav/sidenav.js]: What is ^ this doing ?

File: src/components/sidenav/sidenav.js (hunk 1 above)
Comment (crisbeto) [inline src/components/sidenav/sidenav.js]: Hmm yeah, good point. I'll change it.

File: src/components/sidenav/sidenav.js (hunk 2 above)
Comment (crisbeto) [inline src/components/sidenav/sidenav.js]: The `register` method returns a method that can be used to de-register the component. Here we de-register the instance, because it was using the old id, and we register it again with the new one.

Comment (ThomasBurleson) [inline src/components/sidenav/sidenav.js]: Ok... just add a sidecomment: `// $ctrol.destroy() simply de-registers the component`

File: src/components/sidenav/sidenav.js [hunk 3]
```diff
@@ -505,5 +503,21 @@ function SidenavController($scope, $element, $attrs, $mdComponentRegistry, $q) {
   self.toggle = function() { return self.$toggleOpen( !$scope.isOpen );  };
   self.$toggleOpen = function(value) { return $q.when($scope.isOpen = value); };
 
-  self.destroy = $mdComponentRegistry.register(self, $attrs.mdComponentId);
+  // Evaluate the component id.
+  var rawId = $attrs.mdComponentId;
+  var hasDataBinding = rawId && rawId.indexOf($interpolate.startSymbol()) > -1;
```
Comment (EladBezalel) [inline src/components/sidenav/sidenav.js]: Why isn't that check happens on the directive?

File: src/components/sidenav/sidenav.js [hunk 4]
```diff
@@ -505,5 +503,21 @@ function SidenavController($scope, $element, $attrs, $mdComponentRegistry, $q) {
...
+  var componentId = hasDataBinding ? $interpolate(rawId)($scope.$parent) : rawId;
+
+  // Register the component.
+  self.destroy = $mdComponentRegistry.register(self, componentId);
+
+  // Watch and update the component, if the id has changed.
+  if (hasDataBinding) {
+    $attrs.$observe('mdComponentId', function(id) {
+      if (id && id !== self.$$mdHandle) {
```
Comment (EladBezalel) [inline src/components/sidenav/sidenav.js]: $$mdHandle?

File: src/components/sidenav/sidenav.js (hunk 3 above)
Comment (crisbeto) [inline src/components/sidenav/sidenav.js]: It's not a directive, it's just the attribute that you use to pass the id. I'm not sure it make sense for it to be a directive since it's just a string.

File: src/components/sidenav/sidenav.js (hunk 4 above)
Comment (crisbeto) [inline src/components/sidenav/sidenav.js]: That's the id that is assigned when an element is registered with the `$mdComponentRegistry`. (https://github.com/angular/material/blob/master/src/core/services/registry/componentRegistry.js#L64)

File: src/components/sidenav/sidenav.js (hunk 3 above)
Comment (EladBezalel) [inline src/components/sidenav/sidenav.js]: It can be an attribute directive that checks if it should watch for changes or not (like mdColors does)

Comment (crisbeto) [inline src/components/sidenav/sidenav.js]: It still seems redundant and won't be immefiately obvious where the id is coming from. In this case it's right next to the initialization.

File: src/components/sidenav/sidenav.js (hunk 4 above)
Comment (ThomasBurleson) [inline src/components/sidenav/sidenav.js]: why not call it `self.componentId` ?

Comment (crisbeto) [inline src/components/sidenav/sidenav.js]: `self.componentId` isn't actually being declared, it's only in the `$attrs`, `$$mdHandle` is the one that keeps track of the current id.

File: src/components/sidenav/sidenav.js (hunk 3 above)
Comment (crisbeto) [inline src/components/sidenav/sidenav.js]: As per the discussion on Slack, let's keep this in here for now and do a more generic solution if the need for one comes up.
