### PR TITLE
fix(gestures): slider and swipe touch

### LINKED ISSUE #10294: md-slider not working in chrome on windows touch devices
**Actual Behavior**

Drag of slider is not working properly only click is working. The slider can be dragged for a short time but is lost after a few pixels. When the slider is configured as discrete the slider always jumps to the beginning when dragged. Might be related to #10187

**CodePen (or steps to reproduce the issue)**

Open the demo link of angular material in Chrome 55 on a windows touch device (e.g. Surface, WinPad etc.)
https://material.angularjs.org/latest/demo/slider

**Angular Versions**

Angular Version: 1.5.8
Angular Material Version: 1.1.1

**Additional Information**

Browser Type: Chrome
Browser Version: 55.0.2883.87 m
OS: Windows 8 & 10 (on touch device)

### PR DESCRIPTION
**Pull request by EladBezalel**
- slider was based on mdGesture service that set `touch-action: pan-x` in case the gesture was horizontal;
according the [google pointer-events documentation](https://developers.google.com/web/updates/2016/10/pointer-events):
```
pan-x: The browser is only allowed to perform the horizontal scroll default action.
```
that means we should had enabled `pan-y` and vice-versa instead.

- swipe directive didn't had any `touch-action` css styles, added `touch-action: none` on the directive element on link

fixes #10294, #10187, #10145

### CODE REVIEW

File: src/core/services/gesture/gesture.js [hunk 1]
```diff
@@ -248,7 +248,7 @@ function MdGesture($$MdGestureHandler, $$rAF, $timeout) {
         if (touchActionProperty) {
           // We check for horizontal to be false, because otherwise we would overwrite the default opts.
           this.oldTouchAction = element[0].style[touchActionProperty];
-          element[0].style[touchActionProperty] = options.horizontal === false ? 'pan-y' : 'pan-x';
+          element[0].style[touchActionProperty] = options.horizontal ? 'pan-y' : 'pan-x';
```
Comment (DevVersion) [inline src/core/services/gesture/gesture.js]: I think I initially wrote that lines and I think it was intentional to only allow `pan-x` for horizontal gestures and `pan-y` for vertical gestures.

Can you explain more why this needs to be the other way around?

| State | Value | Description |
| ----- | ------ | --- |
| horizontal | pan-x | Only recognize X-Axis movement s |
| vertical |  pan-y | Only recognize Y-Axis movements |

**Comment by jelbourn** [comment]
Tried this with Chrome 55 and Edge on a MS Surface and everything was peachy. Thanks! LGTM

File: src/core/services/gesture/gesture.js (hunk 1 above)
Comment (EladBezalel) [inline src/core/services/gesture/gesture.js]: Cause it's the other way around:

 | Value | Description |
| ------ | --- |
| pan-x | The browser is only allowed to perform the horizontal scroll default action. |
|  pan-y | The browser is only allowed to perform the vertical scroll default action. |

There for we need

| State | Value |
| ----- | ------ |
| horizontal | pan-y |
| vertical |  pan-x |

**Comment by crownofapollo** [comment]
This now break my application; I have an md-tabs with md-dynamic-height inside a layout-full and an md-content. Vertical scrolling in the md-content no longer works.

**Comment by xcafebabe** [comment]
Same scenario described by @crownofapollo . Vertical srolling in md-content no longer works.

**Comment by EladBezalel** [comment]
@xcafebabe i will look into it asap

**Comment by xcafebabe** [comment]
Hi @EladBezalel,

I will send you two codepens with same code, turn on Device mode in Chrome and swipe up and down.

With 1.1.2: swipe up-down works.
http://codepen.io/xcafebabe/pen/zNaJBq

With 1.1.3: swipe up-down does not work
http://codepen.io/xcafebabe/pen/NdzLbJ

Tested with
Jessie Debian, Chrome 56.0.2924.87 (64-bit) and without using touch screen, but I'm also experiencing same behavior in an Android 6 mobile device (LG G3), either using google chrome app or an android webview, both version 55.0.2883.91.

Nevertheless thank for the great work you are doing! :)

**Comment by Paul-Reed** [comment]
@EladBezalel Thanks for looking at this, but I'm also unable to swipe up-down too - Android 6 (HTC1)
Issue seems to be confined to Chrome browser, as works fine on Firefox...
