### PR TITLE
fix(menu-bar): z-index not restored on menu close

### LINKED ISSUE #11235: menuBar: failure to remove md-has-open-menu selector
### Bug:
When md-menu is used inside md-toolbar after clicking on some nested menu option, the md-toolbar still contains md-has-open-menu which causes z-index of toolbar to be increased all the time.

### What is the expected behavior?
md-toolbar should remove md-has-open-menu after closing the md-menu.

### What is the current behavior?
md-toolbar contains md-has-open-menu even after closing the md-menu.

##### Detailed Reproduction Steps: 
1. Select on _View_ menu.
2. Click on _Mode --> Edit_.
3. Now look at the md-toolbar, it will still contain .md-has-open-menu.

### What is the use-case or motivation for changing an existing behavior?
The z-index caused because of md-has-open-menu breaks UI for some other elements(for ex: md-sidenav ui breaks, since its z-index is only 60 while that has 100)
screenshot from 2018-04-16 19-53-58

### Which versions of AngularJS, Material, OS, and browsers are affected?
The issue was there from v1.1.1 till now v1.1.8

### Is there anything else we should know? Stack Traces, Screenshots, etc.
screenshot from 2018-04-16 18-56-34

### PR DESCRIPTION
**Pull request by oliversalzburg**
When an mdMenuBar contains a menu and that menu is opened, the menu bar will receives a CSS class that ultimately affects its z-order. When the menu is closed, the CSS class is supposed to be removed from the menu bar.

When the menu has multiple levels, the menu hierarchy can not be correctly resolved upon menu closure. This results in the CSS class not being removed from the menu bar.

I assumed that this failure is mostly due to the attempt to detect menu structure through DOM traversal, which will not work in this case as the menu hierarchy is not directly reflected in the DOM structure (menus are attached to the body instead).

Fixes #11235

## PR Checklist
Please check that your PR fulfills the following requirements:
- [X] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [x] Tests for the changes have been added or this is not a bug fix / enhancement
- [X] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?
```
[X] Bugfix
[ ] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #11235

## What is the new behavior?
I store a reference to the original menu bar controller to establish the hierarchy when handling the menu closure. This way the CSS class is properly removed from the menu bar and Z order is restored.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

File: src/components/menu/js/menuDirective.js [hunk 1]
```diff
@@ -258,6 +258,7 @@ function MenuDirective($mdUtil) {
   function link(scope, element, attr, ctrls) {
     var mdMenuCtrl = ctrls[0];
     var isInMenuBar = !!ctrls[1];
+    var mdMenuBarCtrl = ctrls[1];
```
Comment (Splaktar) [inline src/components/menu/js/menuDirective.js]: What's the value when not in a menu bar? `null`? `undefined`? If that's the case, then I suppose this is fine in that case, but I want to be sure that it's not something else.

File: src/components/menu/js/menuDirective.js [hunk 2]
```diff
@@ -275,7 +276,7 @@ function MenuDirective($mdUtil) {
 
     element.append(menuContainer);
     menuContainer[0].style.display = 'none';
-    mdMenuCtrl.init(menuContainer, { isInMenuBar: isInMenuBar });
+    mdMenuCtrl.init(menuContainer, { isInMenuBar: isInMenuBar, mdMenuBarCtrl : mdMenuBarCtrl });
```
Comment (Splaktar) [inline src/components/menu/js/menuDirective.js]:
```suggestion
    mdMenuCtrl.init(menuContainer, { isInMenuBar: isInMenuBar, mdMenuBarCtrl: mdMenuBarCtrl });
```

**Comment by oliversalzburg** [comment]
Thanks for the quick review! I'll get back to it later tonight.

File: src/components/menu/js/menuDirective.js (hunk 1 above)
Comment (oliversalzburg) [reply src/components/menu/js/menuDirective.js]: It appears to be `null` in that case.

File: src/components/menu/js/menuDirective.js (hunk 2 above)
Comment (oliversalzburg) [reply src/components/menu/js/menuDirective.js]: Thanks for the suggestion. I'll make sure to apply this in my next change.

**Comment by oliversalzburg** [comment]
I can't get ChromeHeadless to work in the DevContainer I'm using. I can't properly write the tests like this. I might try a couple of pushes and see what I get out of CircleCI, but I might have to temporarily downgrade some machine to Node 10 to finish this later.

**Comment by oliversalzburg** [comment]
Alright, those were though to write, but I think I got something acceptable.

In the `should close when clicking on a nested menu item` test, I also wanted to spy on the `close()` of the nested menu controller, but I have no idea how to retrieve it. I opted to skip that check. If you feel like it should be added, please help me out with that controller reference.

In general, I didn't add tests specifically for the existence of the class, but focused on the general closing behavior that was already under test by existing tests. These tests included assertions for the removal of the `md-has-open-menu` class. So it seemed to make most sense to just extend this area of the test suite to cover more deeply nested menus.

**Comment by Splaktar** [comment]
> I might have to temporarily downgrade some machine to Node 10 to finish this later.

I'm not sure if you're on Windows or not, but NVM is one of a few options for quickly switching your NodeJS installation. The most mature one is macOS, but there is a separate version for Windows as well (plus another option or two).

**Comment by oliversalzburg** [comment]
Yeah, I worked with nvm/nvs/... in the past (and I'm on Windows using bash). It always ended up causing more problems than it solved.

I opted to create a quick Hyper-V Windows Development VM. Worked well enough. Thanks for the suggestion though :)

**Comment by oliversalzburg** [comment]
Should I rewrite the commit message to use `fix(menu-bar):` as well?

**Comment by Splaktar** [comment]
That would be helpful, thank you.
