### PR TITLE
fix(panel): allow numbers in offset methods

### LINKED ISSUE #9604: mdPanel: assume that number is in pixels
Currently passing in a plain number doesn't work with the `withOffsetX` and `withOffsetY` methods, because they only accept CSS units. In this case we should append the `px` unit automatically.

Referencing #9564.

### PR DESCRIPTION
**Pull request by crisbeto**
Allows for numbers to be pass to the `withOffsetX` and `withOffsetY` methods, assuming that the units are pixels.

Fixes #9604.

CC @ErinCoughlan @bradrich

### CODE REVIEW

File: src/components/panel/panel.js [hunk 1]
```diff
@@ -2553,3 +2553,12 @@ function getElement(el) {
       document.querySelector(el) : el;
   return angular.element(queryResult);
 }
+
+/**
+ * Adds units to a number value.
+ * @param {number} value
```
Comment (ErinCoughlan) [inline src/components/panel/panel.js]: `@param {string | number} value`

**Comment by crisbeto** [comment]
@ThomasBurleson this should be ready for presubmit.
