### PR TITLE
fix(compiler): $onDestroy hook not called

### LINKED ISSUE #11847: mdCompiler: $onDestroy lifecycle hook never called
## Bug

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Use `$mdPanel` to instantiate a controller instance for a dialog.
1. The `$onInit` lifecycle hook is invoked by the compiler as expected.
1. Destroy the panel.

### What is the expected behavior?
The `$onDestroy` lifecycle hook is invoked.

### What is the current behavior?
It is not.

### What is the use-case or motivation for changing an existing behavior?
These are standard AngularJS lifecycle hooks that should be expected to work on all controller instances. _Especially_ since `$onInit` is working as expected.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7
- AngularJS Material: 1.1.20
- OS: Windows
- Browsers: Chrome

### Related issues
- #8153
- #8845
- #10567

### PR DESCRIPTION
**Pull request by oliversalzburg**
## PR Checklist
Please check that your PR fulfills the following requirements:
- [X] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [x] Tests for the changes have been added or this is not a bug fix / enhancement
- [x] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[X] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Even though the `$onInit` lifecycle hook is fully supported, the `$onDestroy` hook isn't. This is unexpected for developers.

## What is the new behavior?
This change introduces a listener for the `$destroy` event on the linked scope. See https://docs.angularjs.org/api/ng/type/$rootScope.Scope#event-$destroy

This implementation closely resembles the AngularJS internal implementation of the lifecycle hook invokation behavior: https://github.com/angular/angular.js/blob/2b28c540ad7ebf4a9c3a6f108a9cb5b673d3712d/src/ng/compile.js#L3298-L3302

Fixes #11847

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

File: src/core/services/compiler/compiler.js [hunk 1]
```diff
@@ -436,6 +436,15 @@ function MdCompilerProvider($compileProvider) {
         // Create the specified controller instance.
         var ctrl = self._createController(options, injectLocals, locals);
 
+        // Registering excisse $destroy listeners should be avoided.
```
Comment (Splaktar) [inline src/core/services/compiler/compiler.js]:
```suggestion
        // Registering extra $destroy listeners should be avoided.
```

File: src/core/services/compiler/compiler.spec.js [hunk 2]
```diff
@@ -482,4 +482,61 @@ describe('$mdCompiler service', function() {
     });
   });
 
+  describe('AngularJS 1.6 lifecycle hooks', function() {
```
Comment (Splaktar) [inline src/core/services/compiler/compiler.spec.js:485]:
```suggestion
  describe('AngularJS 1.6+ lifecycle hooks', function() {
```
