### PR TITLE
fix(button): properly show focus effect

### LINKED ISSUE #8749: Md-button with target blank stays focused after click
**Actual behavior**:
-  What is the issue?

When `md-button` is used with `target="_blank"` it stays focused after click. Using `md-tooltip` with it and hovering after click makes it visible until we click outside the button.
-  What is the expected behavior?

`md-button` should lose focus after click and tooltip should not be visible when button is not hovered.

**CodePen** or Steps to reproduce the issue:
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/WxwpwE
-  Details: Similar behavior reported in kubernetes/dashboard#877

**Angular Versions**: 
-  Angular Version: 1.5.3
-  Angular Material Version: 1.1.0-rc2

**Additional Information**:
-  Browser Type: Chrome/Firefox
-  Browser Version: Latest
-  OS: Ubuntu 14.04

### PR DESCRIPTION
**Pull request by DevVersion**
* Only apply the focus effect for keyboard interaction (as same as it does currently, but not with a random timeout).

Similar to #9827 

 Fixes #8749. References #7963

### CODE REVIEW

File: src/components/button/button.js [hunk 1]
```diff
@@ -162,20 +162,15 @@ function MdButtonDirective($mdButtonInkRipple, $mdTheming, $mdAria, $timeout) {
...
+      element.on('focus', function() {
+        // Only show the focus effect when being focused through keyboard interaction.
+        if ($mdInteraction.getLastInteractionType() === 'keyboard') {
           element.addClass('md-focused');
         }
-      })
-      .on('blur', function(ev) {
+      });
+
+      element.on('blur', function() {
```
Comment (DevVersion) [inline src/components/button/button.js]: Note: This is intentionally now a new statement, because otherwise the indention is ugly and this is just more clear..

File: src/components/button/button.js [hunk 2]
```diff
@@ -162,20 +162,15 @@ function MdButtonDirective($mdButtonInkRipple, $mdTheming, $mdAria, $timeout) {
...
-        $timeout(function(){
-          scope.mouseActive = false;
-        }, 100);
-      })
-      .on('focus', function() {
-        if (scope.mouseActive === false) {
+
+      element.on('focus', function() {
+        // Only show the focus effect when being focused through keyboard interaction.
+        if ($mdInteraction.getLastInteractionType() === 'keyboard') {
```
Comment (clshortfuse) [inline src/components/button/button.js]: Wouldn't this change the existing interaction if a developer focuses an element over Javascript (such as when opening a dialog or a custom component)?

Comment (DevVersion) [inline src/components/button/button.js]: This does not change anything to the existing behavior, just that we now check the global interaction to detect the last interaction.

Focusing manually per `.focus` does not work right now as well, because the `mousedown` event didn't get fired.

This is the approach we wanted to go with the `$mdInteraction` service, as proposed by Marcy. Similar to #9827

Comment (clshortfuse) [inline src/components/button/button.js]: I just some testing and `mousedown` gets fired after `focus` on Chrome. Instead of tracking mouseactive as a `boolean`, I would suggest a timestamp on last mousedown event. Then attach a timeout to the adding of `md-focused`. If mousedown was triggered within a certain time (say 100ms), don't add the class.

Comment (clshortfuse) [inline src/components/button/button.js]: I've had pretty good success with this change I was testing: 
```
if (!element.hasClass('md-no-focus')) {
  // prevent focus on mousedown
  scope.lastMouseDown = null;
  element.on('mousedown', function(event) {
    scope.lastMouseDown = $mdUtil.now();
  })
  .on('focus', function(event) {
    scope.focusTimeout = $timeout(function() {
      if (scope.lastMouseDown && ($mdUtil.now() - scope.lastMouseDown < 500)) {
        return;
      }
      element.addClass('md-focused');
    }, 100);
  })
  .on('blur', function(ev) {
    if (scope.focusTimeout) {
      $timeout.cancel(scope.focusTimeout);
      scope.focusTimeout = null;
    }
    element.removeClass('md-focused');
  });
}
```

**Comment by DevVersion** [comment]
Going to mark this as in progress now, as we have some discussions about it.

File: src/components/checkbox/checkbox.js [hunk 3]
```diff
@@ -54,7 +54,7 @@ angular
  * </hljs>
  *
  */
-function MdCheckboxDirective(inputDirective, $mdAria, $mdConstant, $mdTheming, $mdUtil, $timeout) {
+function MdCheckboxDirective(inputDirective, $mdAria, $mdConstant, $mdTheming, $mdUtil, $timeout, $mdInteraction) {
```
Comment (crisbeto) [inline src/components/checkbox/checkbox.js]: Seems like the `$mdInteraction` import is unused.

File: src/core/services/interaction/interaction.js [hunk 4]
```diff
@@ -129,4 +132,18 @@ MdInteractionService.prototype.onBufferInputEvent = function(event) {
...
+
+/**
+ * @ngdoc method
+ * @name $mdInteraction#isProgrammatic
+ * @description Method to detect whether any interaction happened recently.
+ * @param {number=} checkDelay Time to check for any interaction to have been triggered.
+ * @returns {boolean} Whether there was any interaction or not.
+ */
+MdInteractionService.prototype.isProgrammatic = function(checkDelay) {
+  var delay = angular.isDefined(checkDelay) ? checkDelay : 15;
```
Comment (crisbeto) [inline src/core/services/interaction/interaction.js]: `angular.isNumber` might be more appropriate here.

File: src/core/services/interaction/interaction.js [hunk 5]
```diff
@@ -129,4 +132,18 @@ MdInteractionService.prototype.onBufferInputEvent = function(event) {
...
+};
+
+/**
+ * @ngdoc method
+ * @name $mdInteraction#isProgrammatic
+ * @description Method to detect whether any interaction happened recently.
+ * @param {number=} checkDelay Time to check for any interaction to have been triggered.
+ * @returns {boolean} Whether there was any interaction or not.
+ */
+MdInteractionService.prototype.isProgrammatic = function(checkDelay) {
```
Comment (crisbeto) [inline src/core/services/interaction/interaction.js]: I know that we decided on the naming for this together, but I'm still not sure that `isProgrammatic` is very obvious. It seems like it implies that the service is programmatic. That being said, I don't have any better suggestions at the moment, perhaps other team member can pitch in?

Comment (DevVersion) [inline src/core/services/interaction/interaction.js]: Yeah, Carlos had a great idea here. - `isUserInvoked`.

File: src/components/button/button.spec.js [hunk 6]
```diff
@@ -66,12 +66,51 @@ describe('md-button', function() {
...
+  }));
+
+  it('should apply focus effect when programmatically focusing', inject(function ($compile, $rootScope){
+    var button = $compile('<md-button>')($rootScope.$new());
+
+    $rootScope.$apply();
+
+    button.triggerHandler('focus');
+
+    expect(button[0]).toHaveClass('md-focused');
```
Comment (crisbeto) [inline src/components/button/button.spec.js]: AFAIK you don't have to fetch the DOM node here. `expect(button).toHaveClass('md-focused')` should work as well.

Comment (DevVersion) [inline src/components/button/button.spec.js]: Valid and changed it.. But just for your information, a lot of other tests are doing the same and I don't want to diff the whole test now.

Comment (crisbeto) [inline src/components/button/button.spec.js]: That's why I didn't make it a blocking request. It's basically the same, it just looks nicer.

Comment (DevVersion) [inline src/components/button/button.spec.js]: Yeah, changed it for the tests I've added.
