### PR TITLE
fix(select): Fix duplicates in label.

### LINKED ISSUE #9442: md-select: selected item label is shown twice when md-option list changes
**Actual Behavior**:
 -  `What is the issue? *` If an item is selected and the option list (`<md-option ng-repeat="...">`) changes the select box contains the label of the selected item twice (as if it was selected multiple times): "value, value".  
When later on a digest cycle runs for the scope of the md-select (e.g. by opening the select box again) the label is updated correctly.
 -  `What is the expected behavior?` The selected value should only be shown once as label.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/WxqkyA
 -  `Details:` Click the "Update options" button to see the issue

While checking if it's related to changes in our application code (which it is not) I already found out that the `syncLabelText()` method is called multiple times. The first time is okay, but the next calls create the wrong label because the `<md-option>` elements are contained twice in the `<md-select-menu>` and both elements with the current value are marked as "selected". Looks like there's a mix of old and new `<md-option>` elements in the DOM.

**Angular Versions**: *
 -  `Angular Version:` 1.4.12, 1.5.5
 -  `Angular Material Version:` 1.1.0 stable (reproducable since 1.1.0-rc2)

**Additional Information**:
 -  `Browser Type: *` any
 -  `Browser Version: *` any
 -  `OS: *` any
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

### PR DESCRIPTION
**Pull request by topherfangio**
Occasionally, `ng-repeat` appears to modify the DOM in such a way that it allows duplicates of selected items. When this happens, the `md-select` has issues displaying the proper label.

Add a quick filter to ensure there are no duplicate selections in our labels.

NOTE: I was unable to reproduce this in a spec; it appears to be related to the scope digests and never happens in the spec. I did update one of the demos to do some manual testing and ensure this fix works as expected, but it didn't have any real use inside of the demo so I removed it before submission.

Fixes #9442.

### CODE REVIEW

File: src/core/util/util.js [hunk 1]
```diff
@@ -799,6 +799,23 @@ function UtilFactory($document, $timeout, $compile, $rootScope, $$mdAnimate, $in
...
+     *    myArray.filter($mdUtil.uniq) => [1, 2, 3, 4]
+     *
+     * @param value
+     * @param index
+     * @param self
+     *
+     * @returns {boolean}
+     */
+    uniq: function(value, index, self) {
+      return self.indexOf(value) === index;
```
Comment (crisbeto) [inline src/core/util/util.js]: This is a pretty simple check and I don't think it makes sense to have it as a util, considering that it's only used it one place as well.

Comment (topherfangio) [inline src/core/util/util.js]: It is basic, but I've wanted it a few times and used some other approach. Although it's currently only in one place, I think there are lots of other places where we could leverage it.

Comment (crisbeto) [inline src/core/util/util.js]: Wouldn't it make sense to have the filtering inside of `uniq` in that case? That's how lodash's implementation works.

Comment (topherfangio) [inline src/core/util/util.js]: @crisbeto You mean something like `$mdUtil.uniq(myArray)` and have it call the `filter()` function internally? I guess so. I'll update the code.

Comment (crisbeto) [inline src/core/util/util.js]: Exactly. I'm not sure that just having the predicate function makes sense in a service.

**Comment by ErinCoughlan** [comment]
@topherfangio What's the status on this PR? We have some Googlers also reporting this issue.

File: src/core/util/util.js [hunk 2]
```diff
@@ -832,6 +832,23 @@ function UtilFactory($document, $timeout, $compile, $rootScope, $$mdAnimate, $in
...
+    },
+
+    /**
+     * When used with the Array.filter() method; provides an easy mechanism for removing duplicates
+     * from an array.
+     *
+     *    var myArray = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4];
+     *    myArray.filter($mdUtil.uniq) => [1, 2, 3, 4]
+     *
+     * @param value
```
Comment (ErinCoughlan) [inline src/core/util/util.js]: Can you add types to these params?

File: src/core/util/util.js (hunk 1 above)
Comment (ErinCoughlan) [inline src/core/util/util.js]: I think `uniq` should return the filtered list without any duplicates. Otherwise, it seems like a lot of extra overhead for using the util.

**Comment by topherfangio** [comment]
@ErinCoughlan Fixed `mdUtil.uniq()` and added param types as requested.

This is a bit of a band-aid which removes duplicate labels caused by an issue with `ng-repeat` allowing duplicate elements in the DOM. I tried a few other fixes, but I think a more proper fix will require major rewrites of the select component.

**Comment by topherfangio** [comment]
Testing can be done by checking out this PR locally and viewing http://codepen.io/topherfangio/pen/yaKWAB?editors=1010 which pulls Material from localhost.
