### PR TITLE
fix(mdTooltip): AngularJS 1.3.20 test failures.

### LINKED ISSUE #10114: fix(mdTooltip): AngularJS 1.3.20 test failures.
**Actual Behavior**:
 -  `What is the issue? *` Several errors are occurring in the tooltip test spec with AngularJS 1.3.20.
 -  `What is the expected behavior?` No errors!

**Angular Versions**: *
 -  `Angular Version:` 1.3.20
 -  `Angular Material Version:` Latest

### PR DESCRIPTION
**Pull request by bradrich**
The test failures were occurring due to the tooltip using the panel API. All requests to destroy the scope need to also be accompanied by requests to destroy the panel.

Fixes #10114

### CODE REVIEW

File: src/components/tooltip/tooltip.js [hunk 1]
```diff
@@ -311,6 +312,7 @@ function MdTooltipDirective($timeout, $window, $$rAF, $document, $interpolate,
       }
 
       function onElementDestroy() {
+        panelRef && panelRef.destroy();
```
Comment (ThomasBurleson) [inline src/components/tooltip/tooltip.js]: Why is this needed when you have L300 ?

Comment (bradrich) [inline src/components/tooltip/tooltip.js]: L300 occurs when the tooltip's scope is destroyed. L315 occurs when the parent element's scope is destroyed.

Comment (bradrich) [inline src/components/tooltip/tooltip.js]: You are right about this @ThomasBurleson. It should only be on L300. I will update this asap.
