### PR TITLE
fix(tabs): show a visual indication of tab focus

### LINKED ISSUE #11384: tabs: visual indicator of focus is missing
#### CodePen and steps to reproduce the issue:
When you go through the page using tab key (for example, tabs demo) you can see no indicator of that the md-tabs element have recieved focus. But if you use arrow key to navigate through md-tabs, visual indicator appears, and keeps working properly. 

#### Detailed Reproduction Steps: 
1. Go to Tabs Demo Page https://material.angularjs.org/1.1.5/demo/tabs
1. Press tab long enough, to get to ONE/TWO/THREE tabs under Dynamic Height example
1. See that there is no visual indicator of focus
1. Use left and write arrows
1. See that now visual indicator of focus appeared

### What is the expected behavior?
Visual indicator appears immediately that the focus is set on md-tabs element. 

### What is the current behavior?
Visual focus is not present than it should be. 

### What is the use-case or motivation for changing an existing behavior?
Accessibility guideline: "Confirm that a visual indicator is present for each element that currently has keyboard focus."

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: The one used in AngularJS Material demos
- AngularJS Material: 1.1.10 (could see the issue in current demo)
- OS: Mac OS
- Browsers: Chrome, Safari
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
[Screenshot with right and wrong version](https://docs.google.com/a/google.com/presentation/d/e/2PACX-1vS3NMxkq9Ob6N0coSZ3Mp6wSsGOXJSFUhYTaoZGMA0ou_0ipr-HojsFBk2UFroU6_sunKbvY53sIfjG/pub?start=false&loop=false&delayms=3000)

### PR DESCRIPTION
**Pull request by codymikol**
the visual highlighting of focused tabs was not functioning

Fixes #11384

## PR Checklist
Please check that your PR fulfills the following requirements:
- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [ ] Tests for the changes have been added or this is not a bug fix / enhancement
- [ ] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently when tabbing to an md-tab, there is no visual indication of focus.

This was happening because the md-dummy tab used to track has-focus on $mdTabsCtrl with ng-focus, but this was removed in [this](https://github.com/angular/material/commit/072f8328391c884b7ebc1ef49f4dc3e6c02e636c) commit

Issue Number: #11384

## What is the new behavior?

Now when tabbing to an md-tab the proper focused styling will be applied.

There seems to be two things required to fix this issue.

Firstly, ng-focus and ng-blur on md-dummy-tab are used to toggle the $mdTabsCtrl.hasFocus flag. This is important because the md-focused style is applied depending on the truthiness of the tabsController hasFocus method. This hasFocus method is partly dependent on $mdTabsCtrl.hasFocus being true.

Secondly, the tabindex of the md-tabs-canvas is set to 0. I'm really not exactly sure why this is necessary as I would expect the tabIndex to default to 0 and it is otherwise not set from what I can tell. If this is not set explicitly to 0, ng-focus will not be triggered when tabbing to the md-tabs. This means that the $mdTabsCtrl.redirectFocus method will not be called and focusing of the tab will not happen. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: src/components/tabs/js/tabsDirective.js [hunk 1]
```diff
@@ -146,6 +146,7 @@ function MdTabs ($$mdSvgRegistry) {
             '<md-icon md-svg-src="'+ $$mdSvgRegistry.mdTabsArrow +'"></md-icon> ' +
           '</md-next-button> ' +
           '<md-tabs-canvas ' +
+              'tabindex="0" ' +
```
Comment (Splaktar) [inline src/components/tabs/js/tabsDirective.js]: Please go back to what the old commit did `'tabindex="{{ $mdTabsCtrl.hasFocus ? -1 : 0 }}" ' +`. This allows for shift+tab to escape from the tabs control. With it staying `0` all of the time, shift+tab gets stuck and can't get out of the tabs control.

**Comment by codymikol** [comment]
You're definitely right, changed 👍
